### ISSUE TITLE
CA certificate issue with https private tracker

### ISSUE THREAD

**Issue by gotjoshua** [binhex/arch-rtorrentvpn#10]
In rutorrent i get this error:
Tracker Status: Tracker: [Peer certificate cannot be authenticated with given CA certificates]

I raise the issue here, because my local NAS running the synology build of deluge has no problem with the tracker.

I have STRONG_CERTS=no set as an env var...

I saw this thread but didn't manage:
https://bbs.archlinux.org/viewtopic.php?id=41721

any help?

**Comment by binhex** [comment]
This warning is purely tracker related and isn't related to deluge, the warring maybe triggered by the fact your coming from a VPN IP which would explain why your not seeing the same message on your synology  deluge instance. Best bet is to talk to the admins of the private site and see what they say, they will be able to see the logs.

**Comment by gotjoshua** [comment]
Thanks for the reply @binhex, 

Well i did not enable VPN yet, i want to be sure everything is working without it at first.

Just got out of a chat with the tracker helpdesk, and they assured me it is because of outdated certificates.

Found this:
https://wiki.archlinux.org/index.php/RTorrent#CA_certificates
which suggests:
To use rTorrent with a tracker that uses HTTPS, do the following as root:
```
# cd /etc/ssl/certs
# wget --no-check-certificate https://www.geotrust.com/resources/root_certificates/certificates/Equifax_Secure_Global_eBusiness_CA-1.cer
# mv Equifax_Secure_Global_eBusiness_CA-1.cer Equifax_Secure_Global_eBusiness_CA-1.pem
# c_rehash
```
And from now on run rTorrent with:
```
$ rtorrent -o http_capath=/etc/ssl/certs
```
But I am not sure how to get that to persist within the docker...

Seems to be a known rtorrent issue with https trackers.

Any ideas?

**Comment by binhex** [comment]
ahh interesting stuff, ok i would guess the above command would go in your rtorrent.rc file, that doesnt looks like an xmlrpc command to me, give it a try and please let me know if it fixes the issue.

**Comment by binhex** [comment]
assuming issue is fixed, please re-open if this isnt the case.
