### ISSUE TITLE
Not detecting correct external IP address

### ISSUE THREAD

**Issue by tomatpasser** [binhex/arch-rtorrentvpn#104]
Docker host: Debian 8 Jessie
VPN provider: AirVPN

In supervisord.log I see that none of the detection methods work and I get

`[warn] Cannot determine external IP address, exhausted retries setting to tunnel IP '10.18.136.125'`

I tried to detect it after the container has been connect for a few seconds by running the commands

```
docker exec -it rtorrent-openvpn bash
VPN_DEVICE_TYPE=tun0
source /home/nobody/getvpnip.sh 
source /root/getvpnextip.sh 
source /home/nobody/rtorrent.sh
```

which works. It detects and prints the correct IP address.
It seems like the VPN tunnel is not completely set up when the detection script is executed which causes the drill and curl commands to fail.

**Comment by binhex** [comment]
`It seems like the VPN tunnel is not completely set up when the detection script is executed which causes the drill and curl commands to fail.`

thats odd, as the scripts are set as 'up scripts' via openvpn, so openvpn should be fully up when the script runs, i guess i could put a small delay in place, any ideas on exactly what "a few seconds" is in real terms?

**Comment by grantbey** [comment]
I'm getting this same error on the delugeVPN, sabnzbdVPN and qbittorrentVPN containers.

What are the consequences of the external IP being incorrectly set?

**Comment by TRaSH-** [comment]
i'm noticing this as well lately.

```
[info] rTorrent listening interface IP 0.0.0.0 and VPN provider IP 10.xx.xx.xx different, marking for reconfigure

2019-06-30 01:13:59,320 DEBG 'watchdog-script' stdout output:
[info] rTorrent not running

2019-06-30 01:13:59,336 DEBG 'start-script' stdout output:
Error: could not find any address for the name: `ns1.google.com'

2019-06-30 01:13:59,340 DEBG 'start-script' stdout output:
Error: could not find any address for the name: `resolver1.opendns.com'

2019-06-30 01:13:59,362 DEBG 'start-script' stdout output:
[warn] Cannot determine external IP address, exhausted retries setting to lo '127.0.0.1' 
```

**Comment by binhex** [comment]
ok so ive added in an additional dns check script, this will verify name resolution is working, and retry if it isnt, once it is working it will move onto the external ip script.

to test this change please pull down binhex/arch-rtorrentvpn:test

let me know if it fixes the issue.

**Comment by TRaSH-** [comment]
`2019-07-03 19:06:14,204 DEBG 'start-script' stdout output:
Error: could not find any address for the name: `ns1.google.com'

2019-07-03 19:06:14,209 DEBG 'start-script' stdout output:
Error: could not find any address for the name: `resolver1.opendns.com'

2019-07-03 19:06:14,243 DEBG 'start-script' stdout output:
[warn] Cannot determine external IP address, exhausted retries setting to lo '127.0.0.1'

2019-07-03 19:06:14,319 DEBG 'watchdog-script' stdout output:
[info] rTorrent listening interface IP 0.0.0.0 and VPN provider IP 10.29.128.32 different, marking for reconfigure `

![image](https://user-images.githubusercontent.com/6155095/60611168-f53c5200-9dc5-11e9-8116-4e44004817e0.png)


and that's why it errors out on the tracker,
if not mistaking it should show the ip of the vpn.
but changing to 0.0.0.0 does also work

**Comment by binhex** [comment]
Ok and this is with the test tagged image that I've just created right? I don't see how it could have progressed to the external IP script because it has to check it can resolve names before it can run that script hmmm

**Comment by TRaSH-** [comment]
yes this is with the :test tag
![image](https://user-images.githubusercontent.com/6155095/60614637-94187c80-9dcd-11e9-9459-bfaf891105f6.png)

**Comment by binhex** [comment]
hmm so looking at this from your post above:-

```
2019-07-03 19:06:14,209 DEBG 'start-script' stdout output:
Error: could not find any address for the name: `resolver1.opendns.com'

2019-07-03 19:06:14,243 DEBG 'start-script' stdout output:
[warn] Cannot determine external IP address, exhausted retries setting to lo '127.0.0.1'
```

note how this goes from the first resolver to the end of the script in about 30ms, which is WAY too fast so it looks like its not even attempting to query dns at all, or fallback to web site external ip lookup.

can you attach the whole supervisord.log here, obviously minus passwords and usernames.

**Comment by TRaSH-** [comment]
https://pastebin.com/dzz2GCYi
Hope it isn't a issue that i added the following line in the rotrrent.rc since the issue so the torrents don't error out.
`network.local_address.set = 0.0.0.0 `
normally i didn't have this enabled.
with this setting the torrents at least start without a error.

**Comment by binhex** [comment]
Your lan_network is not correct, from your log:-

2019-07-04 21:06:38.879537 [info] LAN_NETWORK defined as '192.168.2.1/24

It should be 192.168.2.0/24

**Comment by lzrdking71** [comment]
I have pulled down binhex/arch-rtorrentvpn:test and I am still having the same issue. See the below link for my supervisor.log.

https://pastebin.com/NcaEhMSL

**Comment by binhex** [comment]
ok new 'test' tagged build built, this wont fix the issue (whatever it is) but it will hopefully give me more info, please pull down and then paste your supervisord.log file again.

**Comment by lzrdking71** [comment]
I pulled the new "test" tagged build.  See the below link for my supervisor.log.

https://pastebin.com/sJHhd6bX

**Comment by TRaSH-** [comment]
https://pastebin.com/MYZ909LA

**Comment by binhex** [comment]
ok i think i spotted whats going on, can you please pull the newly built 'test' tagged image again, please post your supervisord.log file even if you get success.

**Comment by lzrdking71** [comment]
It looks to have worked and has detected and filled the IP. It did however generate a lot of "Error: error sending query: Error creating socket" errors. See the below link for my supervisor.log.

https://pastebin.com/9fq78nhh

I just want to say I appreciate the hard work you have put into your containers and the help you are giving in getting this fixed. Thank you.

**Comment by binhex** [comment]
excellent news!, ok i can silence the socket errors, that is simply stderr from drill whilst it retries, once ive made this tweak i will produce one more test image which i would like you to test, if thats good then i will push it out as latest.

**Comment by lzrdking71** [comment]
I went ahead and pulled the test build again. It looks to be working correctly to me. See the below link for my supervisor.log.

https://pastebin.com/xp9jArRK

**Comment by binhex** [comment]
Very happy with that, next build will be tagged latest with these changes.

**Comment by binhex** [comment]
ok guys, so ive just made some more cosmetic changes (not related to this issue) tested and it looks good to me, so ive now built the image tagged as 'latest' with all the changes, please let me know if it still looks good, if so i can close this issue.

**Comment by lzrdking71** [comment]
I just pulled latest build and it is working as expected. Well done. Thanks again.

**Comment by lzrdking71** [comment]
@binhex It looks like this is happening again.

2020-08-29 17:10:49,842 DEBG 'start-script' stdout output:
[warn] Cannot determine external IP address, performing tests before setting to '127.0.0.1'...
[info] Show name servers defined for container

IP in the rutorrent settings/bittorent shows 127.0.0.1

You helped fix it before, hopefully an easy fix again.

**Comment by pannal** [comment]
Same here.
