### ISSUE TITLE
Check Port Plugin

### ISSUE THREAD

**Issue by HalianElf** [binhex/arch-rtorrentvpn#105]
The check_port plugin seems to be an old version which no longer seems to works right.

/usr/share/webapps/rutorrent/plugins/check_plugin/action.php (there's a few other minor differences too):
`@$client->fetch("http://www.canyouseeme.org","POST","application/x-www-form-urlencoded","port=".$port."&submit=Check+Your+Port");`

Current version from the rutorrent github has:
`@$client->fetch("https://portchecker.co/check", "POST", "application/x-www-form-urlencoded", "port=".$port."&submit=Check");`

**Comment by jrdnlc** [comment]
I can confirm updating the plugin fixes the port issues.

**Comment by fryfrog** [comment]
This has been mildly annoying for a month or two now, would love to see this working again! :)

**Comment by fryfrog** [comment]
For anyone wondering, you can just drop an updated `check_port` into your `./rutorrent/user-plugins/` folder and it over rides it. You can use [DownGit] (https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/Novik/ruTorrent/tree/master/plugins/check_port) to just snag that folder as a `.zip` file too, for a nice and easy experience.

**Comment by binhex** [comment]
just waiting on aur to update the rutorrent package, this should then include the latest set of plugins

**Comment by binhex** [comment]
hmm bugged the AUR package maintainer, no dice so now directly pulling latest release from github, needed some heavy sed treatment to get all the new plugins to play nicely but i think im there, new image now available give it a spin guys.

**Comment by fryfrog** [comment]
![Screen Shot 2019-04-17 at 9 42 56 AM](https://user-images.githubusercontent.com/87748/56305508-545ac680-60f5-11e9-90b8-9b9d97f8db1b.png)

^ I'm seeing the above, but ...

```
0 ✓ fryfrog@apollo ~ $ sudo docker exec -it rtorrent-tv-vpn /bin/bash
[root@b3b6f4e40dd4 /]# which python
/usr/sbin/python
[root@b3b6f4e40dd4 /]# which unrar
/usr/sbin/unrar
[root@b3b6f4e40dd4 /]# which pgrep
/usr/sbin/pgrep
[root@b3b6f4e40dd4 /]# which php
/usr/sbin/php
```

I'm not sure if mine was like this before though. :/

**Comment by fryfrog** [comment]
In `conf/config.php`, this was the quick fix... but maybe something is wrong w/ shipped PATH or *my* PATH? :/
```
        $pathToExternals = array(
                "php"   => '/usr/sbin/php',
                "curl"   => '/usr/sbin/curl',
                "gzip"  => '/usr/sbin/gzip',
                "id"    => '/usr/sbin/id',
                "stat"  => '/usr/sbin/stat',
                "unrar" => '/usr/sbin/unrar',
                "python" => '/usr/sbin/python',
                "pgrep" => '/usr/sbin/pgrep',
        );
```

**Comment by binhex** [comment]
Lol damn, I have code to fix up all of the paths in that file but forgot to include a check for users with existing config.php, new users will be ok.

I will fix this up tonight

**Comment by binhex** [comment]
Oh and by the way I'm not sure why you have to define the path as PATH does include /usr/bin/ but there you go*shrug* maybe it's a PHP setting somewhere in missing.

**Comment by fryfrog** [comment]
Besides that, its looking fine! Port check works! :)

**Comment by HalianElf** [comment]
The funny thing is the AUR was updated after that file was changed.

**Comment by fryfrog** [comment]
https://aur.archlinux.org/packages/rutorrent/

^ It is still at 3.9, but in its defense that came out two days ago and the last update before that was like 2 years previous :p

**Comment by binhex** [comment]
Aur is still out of date 3.8, flagged about two weeks ago now

**Comment by fryfrog** [comment]
Time to orphan request?

**Comment by binhex** [comment]
ok new commit is in and image is building, this should now (works in testing) alter existing users config.php 
 (no it doesnt replace it) to enable all plugins to work.

**Comment by jrdnlc** [comment]
Just updated and now can't get access to the Webui. It's just stuck on `Loading...`

**Comment by fryfrog** [comment]
I know it doesn't help much, but I just pulled and restarted and mine is going fine. What do you get in `docker logs`?

**Comment by jrdnlc** [comment]
Deleting and re-adding the container fixed it. All good now

**Comment by binhex** [comment]
closing this off, complete.
