### ISSUE TITLE
No Access Over LAN

### ISSUE THREAD

**Issue by jacobkossman** [binhex/arch-rtorrentvpn#106]
Hi. I'm using a custom VPN (still via OpenVPN) and when I run the container with VPN enabled I cannot access flood or anything via local internet (or anywhere else). With VPN off I can access flood. Please let me know what information I can provide.

**Comment by fryfrog** [comment]
When you say VPN, you mean *inside* the Docker right?

Can you show your `docker run` command, w/ anything private obfuscated?

**Comment by jacobkossman** [comment]
> When you say VPN, you mean _inside_ the Docker right?
> 
> Can you show your `docker run` command, w/ anything private obfuscated?

thanks for the reply, after playing around and seeing the forum posts turns out that the LAN cidr has to be set at 24 (even though i'm pretty sure its not but that's probably because it's inside a VM of ESXi.)
