### ISSUE TITLE
Possible to just restart ruTorrent without restarting rTorrent ?

### ISSUE THREAD

**Issue by TRaSH-** [binhex/arch-rtorrentvpn#108]
Is it Possible to just restart ruTorrent without restarting rTorrent ?
Would be nice if that could be possible when i add a theme or plugin so it picks it up.

**Comment by fryfrog** [comment]
The dumb way, you can probably just `docker exec` in and `kill -HUP` the nginx PID.

**Comment by binhex** [comment]
not easily without using docker exec, as fryfrog suggests.
