### ISSUE TITLE
Add fail2ban to protect login

### ISSUE THREAD

**Issue by enoch85** [binhex/arch-rtorrentvpn#109]
In my previous config I used fail2ban to block unwanted login attempts.

**jail.local:**
```
[rutorrent-auth-repeater]
enabled  = true
port     = http,https
filter   = rutorrent-auth
action   = iptables-repeater[name=ruTorrent]
logpath  = /var/log/nginx/error.log
maxretry = 5
findtime = 31536000
bantime  = 31536000
```

**filter**
```
[Definition]
failregex = no user/password was provided for basic authentication.*client: <HOST>
              user .* was not found in.*client: <HOST>
              user .* password mismatch.*client: <HOST>
ignoreregex = </host></host></host>
```

It should be possible in this docker as well.

**Comment by enoch85** [comment]
More info here: https://stuffphilwrites.com/2013/03/permanently-ban-repeat-offenders-fail2ban/

**Comment by GottZ** [comment]
probably a good idea to add a disable switch as env variable for people with custom authenticators in their reverse proxy like me.

**Comment by binhex** [comment]
this is not going happen im afraid, if you want to use fail2ban then your best bet is to create a container with fail2ban and then point it at the config folder with the nginx logs for this container.
