### ISSUE TITLE
How to get that pesky red apostrophe to disappear (with VPN disabled)

### ISSUE THREAD

**Issue by gotjoshua** [binhex/arch-rtorrentvpn#11]
Rutorrent i still reporting that the torrent port is closed in my install.

Interestingly, if i use an online port checker, the port is open.

Is there a trick to getting that red icon to go away and to be sure that i am getting proper upload speeds?

thanks!

**Comment by fryfrog** [comment]
So you're *not* using VPN? (Why not?)

In that case, you'll need to forward the port on your own router. It seems like it'd be reasonable for a non-vpn connection to try using upnp to create a port forward, but I'm not sure if rTorrent can do that.

**Comment by fryfrog** [comment]
It looks like miniupnpc has a upnpc client that would allow this.

https://ptpb.pw/h6HS

**Comment by gotjoshua** [comment]
Thanks. I am running the image on a dedicated server... At first, I wanted to get everything setup without VPN, and then to add the VPN setup later... Do you expect the red apostrophe to go away if i connect via VPN? If so, will you please take the time to explain why?

**Comment by binhex** [comment]
upnp is nasty (security risk), simply defining an additional port for the container and then port forwarding this port on your router will get rid of the red warning - note this is only required when NOT using the vpn (see below).

you dont need to do the above however if you use the vpn feature, as the port forward is done over the tunnel, so you dont need to define a port for the container OR do any sort of port forward on your router BUT you do need to use a VPN provider that allows incoming ports (also called port forwarding). The recommended vpn providers are PIA  or AirVPN, both of which allow incoming ports :-), if you want an easy life go for PIA as i have code that does everything for you automatically, including setting the incoming port.

**Comment by pthfdr-42** [comment]
@binhex 
>upnp is nasty (security risk)

Remember lots of routers here are dumbed down for "user-friendliness" and UPnP is the only way if an open port is desired.Sometimes you cannot simply configure the router, for example, on a public network.  
Also, since most of the BT trackers are being blocked by the GFW, I cannot download nearly anything as DHT does not work.

**Comment by fryfrog** [comment]
Yeah, I agree w/ @binhex that upnp on your own *router* can be a security issue, but *using* upnp to request a port forward isn't. It'll either work and you get the port forward or it *won't* and you won't and you'll be in the same situation as before.

I think it'd be a reasonable thing to add for non-VPN mode.

**Comment by MariusSchiffer** [comment]
Hide.me for example requires UPnP in the tunnel to set up port forwarding. I would really appreciate the addition, maybe with a fair warning.
