### ISSUE TITLE
How can I get this working with traefik?

### ISSUE THREAD

**Issue by sharkymcdongles** [binhex/arch-rtorrentvpn#110]
I have traefik working with all other containers, but for this container it won't redirect to it. I assume it has something to do with the VPN and the network which is why it can only be hit by port forwarding on localhost, but mayeb I am missing something.

My deployment file:

> ---
> - file:
>     path: "{{ path }}"
>     state: directory
>   with_items:
>     - /etc/rtorrent
>   loop_control:
>     loop_var: path
> 
> - name: rTorrent
>   docker_container:
>     name: rtorrent
>     image: binhex/arch-rtorrentvpn:latest
>     state: started
>     hostname: rtorrent
>     pull: yes
>     restart_policy: on-failure
>     restart_retries: 2
>     capabilities:
>       - NET_ADMIN
>     cpu_period: 100000
>     cpu_quota: 150000
>     env:
>       PUID: "{{ p2p_uid }}"
>       PGID: "{{ group_gid }}"
>       VPN_ENABLED: "yes"
>       VPN_PROV: "airvpn"
>       ENABLE_PRIVOXY: "no"
>       ENABLE_FLOOD: "no"
>       ENABLE_AUTODL_IRSSI: "yes"
>       ENABLE_RPC2: "yes"
>       ENABLE_RPC2_AUTH: "yes"
>       LAN_NETWORK: "192.168.1.0/24"
>       NAME_SERVERS: "209.222.18.222,37.235.1.174,8.8.8.8,209.222.18.218,37.235.1.177,8.8.4.4"
>       DEBUG: "false"
>       PHP_TZ: "UTC"
>       UMASK: "000"
>     ports:
>       - "9080:9080"
>     volumes:
>       - "{{ rtorrent_config }}:/config"
>       - "/etc/localtime:/etc/localtime:ro"
>     networks:
>       - name: p2p
>     labels:
>       traefik.docker.network: "p2p"
>       traefik.enable: "true"
>       traefik.basic.frontend.rule: "Host:rutorrent.{{ domain }}"
>       traefik.frontend.auth.basic.users: "{{ rutorrent_basicauth_user }}:{{ rutorrent_basicauth_password | password_hash('md5') }}"
>       traefik.basic.port: "9080"

**Comment by fryfrog** [comment]
```
   location ^~ /rutorrent/ {
        auth_request /auth-2;
        proxy_pass http://192.168.1.2:9080/;
        include conf.d/proxy-settings.conf;
    }
```

If it helps, this is my nginx reverse proxy configuration for it.

**Comment by binhex** [comment]
no other comments, assumed answered.
