### ISSUE TITLE
ruTorrent ports not responding

### ISSUE THREAD

**Issue by nb1dev** [binhex/arch-rtorrentvpn#111]
[supervisord.log](https://github.com/binhex/arch-rtorrentvpn/files/3146212/supervisord.log)

Docker host: Synology

The container seems to launch OK, VPN connexions OK.
But I can't access to both ruTorrent ports 9080 and 9443.
Flood is OK, I can access to port 3000.
I tried with "VPN_ENABLED=no" to check if it's FW related, but same problem.

Any thoughts?

**Comment by fryfrog** [comment]
At a quick glance, it seems like you'd need `ENABLE_RPC2=on` instead of off?

**Comment by fryfrog** [comment]
```
/usr/bin/nginx: error while loading shared libraries: libdl.so.2: cannot open shared object file: Permission denied
```

Kind of looks like nginx doesn't startup?

I'd `docker exec` into the container while it is running and check, `ps aux`... do you see nginx?

**Comment by nb1dev** [comment]
Thank you for your help.

With `docker exec` on my container, i'm not seeing any nginx.

RPC2 seems to be an API to make XML calls from external app, I don't think it's related.
I've tried to run this Docker on another computer (not my Synology) and I can run it as espected.

I'm trying to make this Docker run on my Synology with the same option as on my other computer, so I think it's related to how Synology handle the Docker or the Docker parameters generated with the GUI.

Synology generated run command :

```
docker run \
	--name=rTorrent \
	--hostname=rTorrent \
	--env="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/nobody/bin" \
	--env="HOME=/home/nobody" \
	--env="TERM=xterm" \
	--env="LANG=en_GB.UTF-8" \
	--env="PGID=100" \
	--env="PUID=1026" \
	--env="UMASK=000" \
	--env="PHP_TZ=Europe/Paris" \
	--env="DEBUG=true" \
	--env="NAME_SERVERS=8.8.8.8,8.8.4.4" \
	--env="LAN_NETWORK=192.168.0.0/24" \
	--env="ENABLE_RPC2_AUTH=no" \
	--env="ENABLE_RPC2=no" \
	--env="ENABLE_AUTODL_IRSSI=no" \
	--env="ENABLE_FLOOD=no" \
	--env="ENABLE_PRIVOXY=yes" \
	--env="STRICT_PORT_FORWARD=yes" \
	--env="VPN_PROV=custom" \
	--env="VPN_PASS=pass" \
	--env="VPN_USER=user" \
	--env="VPN_ENABLED=yes" \
	--volume="/volume1/docker/Docker-RuTorrent:/config:rw" \
	--volume="/volume1/downloads/DL-Torrents:/data:rw" \
	--volume="/config" \
	--volume="/data" \
	--network=bridge \
	--privileged \
	-p 0.0.0.0:9443:9443 \
	-p 0.0.0.0:49170:49170 \
	-p 0.0.0.0:3000:3000 \
	-p 0.0.0.0:9080:9080 \
	-p 0.0.0.0:49160:49160 \
	-p 0.0.0.0:8118:8118 \
	-p 0.0.0.0:5000:5000 \
	--restart=no --detach=true -t binhex/arch-rtorrentvpn:latest /bin/bash /root/init.sh
```

**Comment by GottZ** [comment]
the problem is high IOP's on file operations. rutorrent will become pretty much useless as result.
solution: stop using a potato.

if your iops are too intense even flood will stop working.

**Comment by binhex** [comment]
old issue, if still a problem re-raise and attach supervisord.log
