### ISSUE TITLE
all config go default after restarting

### ISSUE THREAD

**Issue by tongt15** [binhex/arch-rtorrentvpn#112]
Hi, I am using unRaid Docker, after restarting the docker, every setting go default

**Comment by fryfrog** [comment]
Sounds like you're not passing in an outside folder for `/config`. All the persistent configuration data is stored there, so if that isn't *outside* the container, it'll get nuked frequently.

Show us your `docker run` command, your compose or what ever unRAID gives you to show how you've configured it.

**Comment by TRaSH-** [comment]
isn't it that most changes in rutorrent don't stick after a reboot,
you need to edit the .rc config file.

**Comment by binhex** [comment]
answered here:- https://github.com/binhex/documentation/blob/master/docker/faq/rtorrentvpn.md
