### ISSUE TITLE
Removal of Flood web ui from next release

### ISSUE THREAD

**Issue by binhex** [binhex/arch-rtorrentvpn#115]
A heads up, next release of this image will NOT include the optional 'Flood' web ui, its become too much of a headache to keep fixing, nearly every time i attempt to build it will fall over during the install of Flood which is annoying to say the least. If you require Flood then your options are:-

1. switch to a named tagged image that includes flood (as in the current image)
or
2. fork my code on github and add in flood and create your own image.

Sorry guys its just too much of a hassle, and IMHO brings very little to the table, other than eye candy.

**Comment by enoch85** [comment]
How will this affect people like me, updating with watchtower? It will try to use the old `-e` ENVs for Flood (no in my case) and fail hard since they don't exist, right?

**Comment by binhex** [comment]
no it wont fail, the env var will still be set but it will do absolutely nothing, so it doesnt matter what its set to. if you want to keep things neat then remove the env var after updating.

**Comment by Dovry** [comment]
Please keep this pinned, remove 'flood' from the description and tags, and add a section to the README, I've been troubleshooting for an hour wondering why Flood wasn't starting.
Browsed through ~20 pages of your forum thread only to finally think of searching the issues here.
