### ISSUE TITLE
Addtional lan ports variable.

### ISSUE THREAD

**Issue by calmcacil** [binhex/arch-rtorrentvpn#116]
Could you please add additional lan ports as a variable so we can define ports that should be able to access lan, Its one of the more annoying things for me as i currently have to login and run a script myself whenever the container is restarted to allow nzbtomedia to inform medusa that downloads are completed. Thanks.

**Comment by fryfrog** [comment]
Does Medusa not have a way to interact w/ torrent client's via API?

**Comment by calmcacil** [comment]
no, medusa is based on sickrage and relies on nzbtomedia scripts.

**Comment by binhex** [comment]
> no, medusa is based on sickrage and relies on nzbtomedia scripts.

im not sure where you got this info from but its just plain incorrect, medusa can indeed talk to most if not all popular usenet/torrent clients via api, i personally run this docker image and medusa communicates with rtorrent/rutorrent via api without issue.
