### ISSUE TITLE
Is there an easy way to use this on a specified network and not a bridge network?

### ISSUE THREAD

**Issue by sharkymcdongles** [binhex/arch-rtorrentvpn#118]
I run watchtower to upgrade this container automatically, but the problem is you cannot assign a static 172 ip on the bridge network or do any aliases, so my sonarr and radarr need to be edited each time to be able to connect when the container is recreated.

When I specify the network my radarr and sonarr are on without bridge it doesn't work. Am I missing something? Sorry if this is a stupid question. I was gonna script something to auto detect ip and put it into sonarr and radarr, but I'd rather just be able to specify rtorrent as the host and be done with it.

**Comment by binhex** [comment]
```
 but the problem is you cannot assign a static 172 ip on the bridge network or do any aliases, so my sonarr and radarr need to be edited each time to be able to connect when the container is recreated.
```

this is not right, you shouldn't be referencing the internal docker bridge network, you use the host's ip address to access the container.

so you should be using http://<your hosts ip address>:<the host port for the web ui>
e.g. http://192.168.1.10:9080
