### ISSUE TITLE
Max torrents supported?

### ISSUE THREAD

**Issue by DirtyCajunRice** [binhex/arch-rtorrentvpn#119]
I see that via the april release you bumped mem to support 2k+ torrents. I am currently at ~5600 and its still running _ok_ . Is there a threshold i should be worried about?

**Comment by binhex** [comment]
This is hard to say what the max can be, but in theory if you have a powerful cpu and fast drives (ideally ssd) and plenty of ram then you can just keep upping the memory and i could imagine you should be able to get well into the 10k+ torrent range, ive heard of people using this image and running 5k+ so 10k should be doable.
