### ISSUE TITLE
ENABLE_FLOOD = both  -  inconsistent pausing 

### ISSUE THREAD

**Issue by gotjoshua** [binhex/arch-rtorrentvpn#12]
When I set this flag:
I can start and pause torrents fine from ruTorrent.
I can see in Flood the results of the above actions.
If I start the torrent from Flood, it works and reflected in ruTorrent.
If I try to pause a torrent from Flood, it is quickly restarted in both clients.

**Comment by binhex** [comment]
yeh not sure what to say really, i dont recommend using both tbh, i would personally stick with rutorrent until flood is mature enough and has all the features you need, closing this off for now as there isnt anything i can do about the issue.
