### ISSUE TITLE
Deleting files, or make large changes makes ruTorrent/rTorrent time out

### ISSUE THREAD

**Issue by enoch85** [binhex/arch-rtorrentvpn#121]
I don't know exactly what changed since you decided to use rTorrent-PS, but after the change I get ALOT more timeouts in the ruTorrent GUI. It typically happen when:
- I delete a torrent (and data) that holds a few GB of data. 
- I delete multiple torrents at once
- I add several torrents at once

It's just like it's trying to catch up, and timeouts for a long period of time, and then comes back by itself. I use RSS as well with a 10 minute interval, maybe worth mentioning.

Are there any setting, or anything I can do myself to speed things up?

**Comment by binhex** [comment]
For me this actually improved when moving to rtorrent-ps, prior to this deletions frequently caused timeouts. There isnt really much else i can do to improve this, your best bet is to raise this as an 'issue' on the rtorrent-ps github repo and see what they come back with as suggestions.

**Comment by enoch85** [comment]
Done
