### ISSUE TITLE
OOM [out of memory] during rtorrent launch

### ISSUE THREAD

**Issue by FreekingDean** [binhex/arch-rtorrentvpn#125]
It seems rtorrent is eating all available memory on launch. it grows to ~10G and then gets killed by  the oom-killer.

I am running this on arch in kubernetes (k3s).
I have run rtorrent-ps using your precompiled package on the host outside of kubernetes & it runs successfully, so something is happening with this container to cause it to OOM [out of memory].

**Comment by binhex** [comment]
maybe this is a incompatibility with kubernetes, unfortunately i dont have the time or resources to debug :-(.

**Comment by Szpadel** [comment]
for whoever that debugging similar issue in the future and found this:

it's caused by very high `ulimit -n` because libtorrent wants to allocate pool of size `sysconf(_SC_OPEN_MAX)`
