### ISSUE TITLE
Missing remote line causes infinite restart

### ISSUE THREAD

**Issue by PhasecoreX** [binhex/arch-rtorrentvpn#130]
In `install.sh` https://github.com/binhex/arch-rtorrentvpn/blob/f53cb0aca9811d251c0bf2df91dcbd9b71e3c96d/build/root/install.sh#L339
this line will exit with status 1 if no `remote` line is found. This causes the script to exit, which means that the `[crit] VPN configuration file ${VPN_CONFIG} does not contain 'remote' line, showing contents of file before exit...` line never happens. If you have Docker automatically restart the container, it will restart over and over, with no indication as to why it's restarting.

Interestingly, I think I got to this point because I managed to kill the container after all the `remote` lines were removed, but before one was added back to the file. Fun times!

**Comment by binhex** [comment]
ahh good catch, i see the set -e is causing the exit due non zero return code from grep, i can fix that up.
