### ISSUE TITLE
Error Trying to access array offset 

### ISSUE THREAD

**Issue by frank3427** [binhex/arch-rtorrentvpn#137]
my log is flooded with these errors
2020-01-17 20:43:38,076 DEBG 'rutorrent-script' stderr output:
2020/01/17 20:43:38 [error] 958#958: *12563 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to access array offset on value of type bool in /usr/share/webapps/rutorrent/plugins/autodl-irssi/getConf.php on line 54PHP message: PHP Notice:  Trying to access array offset on value of type bool in /usr/share/webapps/rutorrent/plugins/autodl-irssi/getConf.php on line 61" while reading response header from upstream, client: x.x.x.x, server: localhost, request: "GET /plugins/autodl-irssi/getlines.php?cid=2031094611&_=1579308355636 HTTP/1.1", upstream: "fastcgi://127.0.0.1:7777", host: "x.x.x.x:9080", referrer: "http://x.x.x.x:9080/"

**Comment by td001** [comment]
Did you manage to solve this @frank3427 ? I am encountering the same errors.

**Comment by frank3427** [comment]
still getting the same error
2020-02-15 08:57:47,888 DEBG 'rutorrent-script' stderr output:
2020/02/15 08:57:47 [error] 919#919: *60103 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to access array offset on value of type bool in /usr/share/webapps/rutorrent/plugins/autodl-irssi/getConf.php on line 54PHP message: PHP Notice:  Trying to access array offset on value of type bool in /usr/share/webapps/rutorrent/plugins/autodl-irssi/getConf.php on line 61" while reading response header from upstream, client: 192.168.10.37, server: localhost, request: "GET /plugins/autodl-irssi/getlines.php?cid=652535446&_=1581778623806 HTTP/1.1", upstream: "fastcgi://127.0.0.1:7777", host: "192.168.10.30:9080", referrer: "http://192.168.10.30:9080/"

**Comment by binhex** [comment]
its apparently an issue with the autodl-irssi plugin which does not support php v7 (v5 only), sadly this is going to be a problem for this container, as php is of course used for all plugins as well as rutorrent, so i wont be downgrading the version of php.

i would encourage you to try and push the autodl-irssi developers to update their plugin to support php 7.4.2, which is the current stable release, and includes security fixes which i very much doubt php v5 has backported

link to autodl-irssi repo:-
https://github.com/autodl-community/autodl-irssi/issues

**Comment by kocane** [comment]
@frank3427  did you ever get a fix for this? been using an old version but it's giving me trouble now and I wanna upgrade.
