### ISSUE TITLE
Synology : Apparmor problem solved

### ISSUE THREAD

**Issue by Ozneb** [binhex/arch-rtorrentvpn#138]
I find a solution to use your marvelous container on my Synology NAS !
To avoid apparmor failed on nginx start, I just copy it to another directory.
**The error**
"/usr/bin/nginx: error while loading shared libraries: libdl.so.2: cannot open shared object file: Permission denied"

**Solution**
In /home/nobody/rutorrent.sh, just modify the end of file :

```
# run nginx in foreground and specify path to pid file
/usr/bin/nginx -g "daemon off; pid /home/nobody/nginx.pid;"
```

with

```
# run nginx in foreground and specify path to pid file
copy --update --archive /usr/bin/nginx /home/nobody/bin/nginx
/home/nobody/bin/nginx -g "daemon off; pid /home/nobody/nginx.pid;"
```
I know you haven't made a container for Synology NAS, but is it possible to include this update in it ?

Thanks a lot

**Comment by binhex** [comment]
interesting!, can you just try a symlink instead?, try the following, let me know if it still works:-

```
ln -s /usr/bin/nginx /home/nobody/
/home/nobody/nginx -g "daemon off; pid /home/nobody/nginx.pid;"
```

**Comment by Ozneb** [comment]
Symlink don't work :
`/home/nobody/bin/nginx: error while loading shared libraries: libdl.so.2: cannot open shared object file: Permission denied`

Hardlink work :
```
ln -f /usr/bin/nginx /home/nobody/bin/
/home/nobody/bin/nginx -g "daemon off; pid /home/nobody/nginx.pid;"
```

1) I can't execute your code "ln -s /usr/bin/nginx /home/nobody/" because there is already a /home/nobody/nginx directory. So I create the link in the /home/nobody/bin/ directory.

2) I use "ln -f" to avoid warning : "ln: failed to create hard link '/home/nobody/bin/nginx': File exists"

**Comment by binhex** [comment]
ok does this work?, just want to bottom out whether a symlink will work at al, or whether it has to be a hardlink:-

```
ln -sf /usr/bin/nginx /home/nobody/bin/
/home/nobody/bin/nginx -g "daemon off; pid /home/nobody/nginx.pid;"
```

**Comment by Ozneb** [comment]
No symbolic link ("ln -s" or "ln -sf") don't work .
**Only hardlink work : "ln -f"**

I use actually :
```
ln -f /usr/bin/nginx /home/nobody/bin/
/home/nobody/bin/nginx -g "daemon off; pid /home/nobody/nginx.pid;"
```

**Comment by binhex** [comment]
ok thanks for confirming, i will run a few tests to make sure it doesnt break anything before releasing.

**Comment by Ozneb** [comment]
Thanks ;)

**Comment by binhex** [comment]
ok test image built, can you please pull down and run:-
```
binhex/arch-rtorrentvpn:test
```
let me know if its runs ok.

**Comment by Ozneb** [comment]
Perfect, it's work like a charm !

**Comment by binhex** [comment]
Image has now been built with latest tag if you're satisfied then please close this issue
