### ISSUE TITLE
Wrong external/announce IP

### ISSUE THREAD

**Issue by Yayq** [binhex/arch-rtorrentvpn#144]
> 2020-03-10 13:43:43,158 DEBG 'start-script' stdout output:
    [info] Checking we can resolve name 'www.google.com' to address...

> 2020-03-10 13:43:43,177 DEBG 'start-script' stdout output:
    [info] DNS operational, we can resolve name 'www.google.com' to address '172.217.22.164 216.239.32.10'

> 2020-03-10 13:43:43,179 DEBG 'start-script' stdout output:
    [info] Attempting to get external IP using Name Server 'ns1.google.com'...

>   2020-03-10 13:43:43,262 DEBG 'start-script' stdout output:
    [info] Successfully retrieved external IP address 216.239.32.10

I can access RuTorrent web fine, I can also download torrents fine. I checked my external IP with curl ifconfig.me which outputs the correct IP address.

Just wondering why it shows 216.239.32.10 (ns1.google.com) as my external IP in the log, and it is also my announce IP for rtorrent.

It works fine and outputs the correct IP when I use an AirVPN ovpn config, seems to change and output the wrong one when I use a Mullvad config.

Log: https://pastebin.com/PK1KVgWa

**Comment by Yayq** [comment]
Closing, 
Updated docker and it fixed the issue.

**Comment by Gin-no-kami** [comment]
I am having the same issue. I tried updating the docker container but the issue is persisting. Any thoughts on what might be causing this?
