### ISSUE TITLE
IP Leak on IRC

### ISSUE THREAD

**Issue by turbo-prinz** [binhex/arch-rtorrentvpn#146]
Hello, 

I expierenced an IP-leak on the irssi irc client: 
> 23:19 -!- Irssi: Connection to irc.hidden.xxx established
> 23:19 !irc.hidden.xxx *** Looking up your hostname...
> 23:19 !irc.hidden.xxx *** Found your hostname (my.real.hostname.xxx)
> 23:24 -!- Irssi: Connection lost to irc.hidden.xxx 
> 23:24 -!- Irssi: Removed reconnection to server irc.hidden.xxx port 7000
> 23:24 -!- Irssi: Looking up irc.hidden.xxx
> 23:24 -!- Irssi: Reconnecting to irc.hidden.xxx [...]

it may only be one seconde before the connection is cut, but obviously the damage was already done.

It seems to be caused because the startup of the client is faster than the startup-script which sets the iptable-rules. See docker-log: 

> [...]
> 2020-03-24 23:19:01,413 INFO success: irssi-script entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
> 2020-03-24 23:19:01,413 INFO success: logrotate-script entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
> 2020-03-24 23:19:01,413 INFO success: pyrocore-script entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
> 2020-03-24 23:19:01,413 INFO success: rutorrent-script entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
> 2020-03-24 23:19:01,413 INFO success: start-script entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
> 2020-03-24 23:19:01,413 INFO success: watchdog-script entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
> 2020-03-24 23:19:01,426 DEBG 'irssi-script' stdout output:
> Script started, output log file is '/home/nobody/typescript'.
> 
> 2020-03-24 23:19:01,465 DEBG 'start-script' stdout output:
> [info] VPN is enabled, beginning configuration of VPN
> 
> 2020-03-24 23:19:01,514 DEBG 'irssi-script' stdout output:
> Script done.
> 
> ### 2020-03-24 23:19:01,518 INFO exited: irssi-script (exit status 0; expected)
> 2020-03-24 23:19:01,518 DEBG received SIGCHLD indicating a child quit
> 2020-03-24 23:19:01,749 DEBG 'start-script' stdout output:
> [info] Default route for container is 172.28.0.1
> 
> 2020-03-24 23:19:01,863 DEBG 'start-script' stdout output:
> [info] Adding 8.8.8.8 to /etc/resolv.conf
> 
> 2020-03-24 23:19:02,138 DEBG 'start-script' stdout output:
> [info] Docker network defined as    172.28.0.0/16
> 
> 2020-03-24 23:19:02,141 DEBG 'start-script' stdout output:
> [info] Adding 192.168.1.1/32 as route via docker eth0
> 
> 2020-03-24 23:19:02,143 DEBG 'start-script' stdout output:
> [info] ip route defined as follows...
> 
> 2020-03-24 23:19:02,144 DEBG 'start-script' stdout output:
> default via 172.28.0.1 dev eth0
> 172.28.0.0/16 dev eth0 proto kernel scope link src 172.28.0.2
> 192.168.1.1 via 172.28.0.1 dev eth0
> 
> 2020-03-24 23:19:02,144 DEBG 'start-script' stdout output:
> 
> 2020-03-24 23:19:02,150 DEBG 'start-script' stdout output:
> iptable_mangle         16384  2
> ip_tables              28672  5 iptable_filter,iptable_nat,iptable_mangle
> x_tables               40960  14 ebtables,ip6table_filter,xt_conntrack,iptable_filter,xt_tcpudp,ipt_MASQUERADE,xt_addrtype,xt_CHECKSUM,xt_nat,ip6_tables,ipt_REJECT,ip_tables,iptable_mangle,xt_mark
> 
> 2020-03-24 23:19:02,151 DEBG 'start-script' stdout output:
> [info] iptable_mangle support detected, adding fwmark for tables
> 
> 2020-03-24 23:19:02,607 DEBG fd 16 closed, stopped monitoring <POutputDispatcher at 139723571654032 for <Subprocess at 139723571653984 with name pyrocore-script in state RUNNING> (stdout)>
> 2020-03-24 23:19:02,607 DEBG fd 20 closed, stopped monitoring <POutputDispatcher at 139723571708976 for <Subprocess at 139723571653984 with name pyrocore-script in state RUNNING> (stderr)>
> 2020-03-24 23:19:02,607 INFO exited: pyrocore-script (exit status 0; expected)
> 2020-03-24 23:19:02,607 DEBG received SIGCHLD indicating a child quit
> 2020-03-24 23:19:02,706 DEBG 'start-script' stdout output:
> [info] iptables defined as follows...
> 
> 2020-03-24 23:19:02,708 DEBG 'start-script' stdout output:
> -P INPUT DROP
> -P FORWARD DROP
> -P OUTPUT DROP
> -A INPUT -s 172.28.0.0/16 -d 172.28.0.0/16 -j ACCEPT
> -A INPUT -i eth0 -p udp -m udp --sport 3000 -j ACCEPT
> -A INPUT -i eth0 -p tcp -m tcp --dport 9080 -j ACCEPT
> [...]

**Comment by binhex** [comment]
You are correct, there was a call to the irssi script in the supervisor configuration which could cause a race condition where irssi started before iptables were in place, this call is not required as i have calls to irssi in the watchdog script, which does do thorough checks before startup (including checks for iptable rules). i have removed the supervisor reference, added in additional logging to irssi and tested and it looks good to me.

Please pull down the latest image and let me know if you think the issue is resolved, if so please comment and close this issue.

**Comment by turbo-prinz** [comment]
Thanks for the quick response!

Looks better now.

**Comment by turbo-prinz** [comment]
Another bug connected to this topic (not as cirtical): 

After starting the container the first time, irssi starts with it's configuration-file missing:

> 14:20 -!- Irssi:  ERROR:  Missing configuration file: /home/nobody/.autodl/autodl.cfg
> [...]

When I quit it manually, it is getting restarted by the watchdog with the correct configuration. May there be another race condition?

**Comment by turbo-prinz** [comment]
Seems like 'rutorrent-script' waits for getting rtorrent started by 'watchdog-script' (which starts rtorrent after irssi), before it creates the links to the autodl.cfg file.

I reopend this issue because it seems like the error is caused by the new changes. If I better open a new one, just tell me.

**Comment by turbo-prinz** [comment]
The latest image from dockerhub works. Thanks for your efforts!

**Comment by binhex** [comment]
thanks for the confirmation!.
