### ISSUE TITLE
 DEBG 'start-script' stdout output:

### ISSUE THREAD

**Issue by frank3427** [binhex/arch-rtorrentvpn#148]
why are we seeing this error, I have tried various changes, but it seems to have stopped witht he latest build

2020-03-31 07:25:00,781 DEBG 'start-script' stdout output:
[warn] Response code 000 from curl != 2xx
[warn] Exit code 7 from curl != 0
[info] 6 retries left
[info] Retrying in 10 secs..

**Comment by binhex** [comment]
see here:- https://forums.unraid.net/topic/75539-support-binhex-qbittorrentvpn/?do=findComment&comment=839097
