### ISSUE TITLE
apparmor denying access to /etc/nginx/nginx.conf

### ISSUE THREAD

**Issue by 00Asgaroth00** [binhex/arch-rtorrentvpn#15]
I've just deployed your this image to a synology nas, but while it boots up, the rutorrent.sh script fires up nginx and it dies with  a permission denied (13) error.

It appears that apparmor, within the container, is denying the access. I cannot run "disable apparmor.service) as the disable command is not on the container.

<code>[1242139.690053] type=1400 audit(1488231847.226:3): apparmor="DENIED" operation="open" parent=26952 profile="/usr/bin/nginx" name="/config/nginx/c
onfig/nginx.conf" pid=27598 comm="nginx" requested_mask="r" denied_mask="r" fsuid=1024 ouid=1024                                                  
[1242240.428781] type=1400 audit(1488231948.050:4): apparmor="DENIED" operation="open" parent=28787 profile="/usr/bin/nginx" name="/config/nginx/c
onfig/nginx.conf" pid=32224 comm="nginx" requested_mask="r" denied_mask="r" fsuid=1024 ouid=1024                                                  
[1242315.634472] type=1400 audit(1488232023.319:5): apparmor="DENIED" operation="open" parent=28787 profile="/usr/bin/nginx" name="/config/nginx/c
onfig/nginx.conf" pid=3151 comm="nginx" requested_mask="r" denied_mask="r" fsuid=1024 ouid=1024                                                   
[1242422.621930] type=1400 audit(1488232130.397:6): apparmor="DENIED" operation="open" parent=28478 profile="/usr/bin/nginx" name="/config/nginx/c
onfig/nginx.conf" pid=8027 comm="nginx" requested_mask="r" denied_mask="r" fsuid=0 ouid=1024
</code>

Any ideas on how I can disable apparmor or possibly create a profile to allow access to the /data/nginx/config/nginx.conf file?

**Comment by binhex** [comment]
have a look here:-
https://www.reddit.com/r/synology/comments/4gpf9d/docker_and_apparmor_issue/ 
this guy had a similar issue on a synology box, only difference is he was trying to run my other docker image, delugevpn, looks like he found a way to turn off apparmor

**Comment by 00Asgaroth00** [comment]
Thanks, I have switched to your deluge image now and that one starts up fine for me (except with an issue with libtorrent, which has a ticket open on that repo). I cannot seem to find a fix in the reddit post you mentioned above, looks like he opened a ticket with synology and didnt share the outcome.

**Comment by goras** [comment]
Was this issue ever resolved? I just tried setting up the latest version of rtorrentvpn (rtorrent-ps-1.1.r43.g8be91ab-1-04) on my Synology DS718+ and I'm experiencing exactly the same issue as the OP. I imagine disabling apparmor all together as mentioned in the reddit post above, is not a viable solution?

**Comment by binhex** [comment]
disabling apparmor is a way of getting this container working so it is a viable solution, whether its a solution you are comfortable with is up to you.

just to be clear, this issue is related to synology only, and needs to be fixed by synology dev's, nothing i can do to work around this issue from my side im afraid.

**Comment by binhex** [comment]
FYI anybody still following this issue, this has now been resolved, thanks to @Ozneb, see here for the fix:-
https://github.com/binhex/arch-rtorrentvpn/issues/138#event-2967714652
