### ISSUE TITLE
"Wait for rTorrent process to start aborted, too many retries" after first deployment

### ISSUE THREAD

**Issue by SlothCroissant** [binhex/arch-rtorrentvpn#150]
I am having issues where rTorrentvpn fails to start after my initial deployment, with error "Wait for rTorrent process to start aborted, too many retries". 

Process:
1) Deploy arch-rtorrentvpn  with details below using a NordVPN .ovpn file in my /config/openvpn folder and no other folders created (to allow the startup to build out all the folders and files needed). This works great, connects, I can load torrents, etc. Debug logs here: https://gist.github.com/SlothCroissant/7b50d48a083058825dd5743205deb80f
2) If I delete the stack and rebuild the stack without touching any volumes, env variables etc, rTorrent fails to start. Debug logs here: https://gist.github.com/SlothCroissant/10cd4755780ce85789741d97ea3f7758

Here's my environment info:

Docker-Compose:
```
version: "2"
services:
  rtorrent:
    image: binhex/arch-rtorrentvpn
    container_name: rtorrent
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_ENABLED
      - VPN_USER
      - VPN_PASS
      - VPN_PROV
      - STRICT_PORT_FORWARD
      - ENABLE_AUTODL_IRSSI
      - ENABLE_RPC2
      - ENABLE_RPC2_AUTH
      - ENABLE_WEBUI_AUTH
      - LAN_NETWORK
      - NAME_SERVERS
      - DEBUG
      - PHP_TZ
      - UMASK
      - PUID
      - PGID
    volumes:
      - /mnt/zfs/docker/rtorrent:/config
      - /mnt/user/NAS/Downloads/qbittorrent:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9080:9080
      - 9443:9443
      - 8118:8118
    restart: always
```

Here are my env variables:
```
      - VPN_ENABLED=yes
      - VPN_USER=$username
      - VPN_PASS=$password
      - VPN_PROV=custom
      - STRICT_PORT_FORWARD=no
      - ENABLE_AUTODL_IRSSI=yes
      - ENABLE_RPC2=yes
      - ENABLE_RPC2_AUTH=no
      - ENABLE_WEBUI_AUTH=no
      - LAN_NETWORK=10.1.0.0/16
      - NAME_SERVERS=1.1.1.1,1.0.0.1
      - DEBUG=true
      - PHP_TZ=America/Chicago
      - UMASK=000
      - PUID=1000
      - PGID=1000
```

The only way to resolve this is to nuke my /config folder (except the openvpn folder) and redeploy the compose stack again.

Thoughts on why this happens and how to resolve it?

**Comment by Martyfree123** [comment]
I have this exact same issue. The /config nuke worked for me once, but is now no longer working :(

**Comment by binhex** [comment]
This has been fixed, please pull latest image
