### ISSUE TITLE
Wireguard config

### ISSUE THREAD

**Issue by cd-rum** [binhex/arch-rtorrentvpn#153]
Any plans to introduce Wireguard options now that it's part of the kernel?

**Comment by binhex** [comment]
not until its officially supported by PIA via native wireguard client, which it currently isn't.

**Comment by DorianRudolph** [comment]
It seems there are official scripts now: https://github.com/pia-foss/manual-connections
The script is not yet really usable because it always connects to the nearest server, but it is easy to adapt.
There is also a script for port forwarding.
