### ISSUE TITLE
Port status is unknown rutorrent

### ISSUE THREAD

**Issue by phi0x** [binhex/arch-rtorrentvpn#155]
Getting port status is unknown. Looks like official rutorrent has patched it:
https://github.com/Novik/ruTorrent/pull/2050

can you update this container?
thanks!

**Comment by dandymike** [comment]
i too am receiving error 'port status unknown'

**Comment by W3AXL** [comment]
Can also confirm, made no changes to my container recently and I'm also now getting "port status unknown"

For reference my VPN provider is Mullvad and I do have the port set up properly on the VPN side of things.

**Comment by rammellzee** [comment]
Ditto, receive the port status unknown error but my settings are definitely correct.

**Comment by binhex** [comment]
this is a plugin issue, it has been fixed upstream so i am looking at incorporating the fix shortly.

**Comment by binhex** [comment]
now fixed in the latest image, please pull down.

**Comment by dandymike** [comment]
confirmed fixed, thank you
