### ISSUE TITLE
External IP not detected

### ISSUE THREAD

**Issue by LiQiuDGG** [binhex/arch-rtorrentvpn#160]
Similar to Issue #104 my container using AirVPN is not detecting the external IP address, and setting it to 127.0.0.1 in rtorrent.  

doing this does work:
```
docker exec -it arch-rtorrent bash
VPN_DEVICE_TYPE=tun0
source /root/getvpnip.sh 
source /root/getvpnextip.sh 
source /home/nobody/rtorrent.sh
```

That is of course after the fact.  For the time being I've added sleep 30 to the beginning of /root/prerunget.sh and that seems to have fixed it in the short term.

This is not an issue with PIA vpn provider, seems to be just with AirVPN.

**Comment by binhex** [comment]
i would like to see a full log please to verify it is retrying, perhaps airvpn is so slow connecting that the retry count isnt large enough!:-
https://github.com/binhex/documentation/blob/master/docker/faq/help.md

**Comment by Zxurian** [comment]
so I think I'm suffering from the same issue here. I'm running unRaid 6.8.3, `binhex-rtorrentvpn` that's up to date as of this post with an AirVPN OpenVPN conf file located in `/config/openvpn`. The docker starts up, but in the log it shows 
```
2020-11-14 23:59:16,614 DEBG 'watchdog-script' stdout output:
[info] rTorrent listening interface IP 0.0.0.0 and VPN provider IP 10.31.224.46 different, marking for reconfigure

2020-11-14 23:59:16,622 DEBG 'watchdog-script' stdout output:
[info] rTorrent not running
```
then the watchdog script waits for rtorrent process to start for several times, then aborts after too many retries.
[supervisord.log](https://github.com/binhex/arch-rtorrentvpn/files/5541880/supervisord.log)

**Comment by binhex** [comment]
> so I think I'm suffering from the same issue here.

you aren't, taken from your log:-
```
[info] Attempting to get external IP using 'http://checkip.amazonaws.com'...
[info] Successfully retrieved external IP address 184.75.221.59
```
you issue is rtorrent is unable to start, this is probably a misconfiguration issue, i suspect a badly configured rtorrent config file, try deleting the config file and it will re-create a default one, this should at least give you the ui then, config file is located at ```/config/rtorrent/config/rtorrent.rc```

**Comment by Zxurian** [comment]
@binhex thank you for your update. GitHub didn't notify me and only checking now. I've switched to your qBittorrent release and everything is working fine now.
