### ISSUE TITLE
PIA API Issues

### ISSUE THREAD

**Issue by Vi1i** [binhex/arch-rtorrentvpn#162]
Not sure if this is something to handle on your end, but the new 'next gen' servers from PIA have been weird. As of several days ago, I am no longer able to connect to PIA, looking through some forums and thought this new script might help.
https://github.com/fm407/PIA-NextGen-PortForwarding/blob/master/pia-nextgen-pf.sh

**Comment by binhex** [comment]
Support for multi remote endpoints and PIA 'Next-Gen' networks now complete, see Q19 and Q20 for details:-
https://github.com/binhex/documentation/blob/master/docker/faq/vpn.md
