### ISSUE TITLE
Bug in libtorrent (rakshasa) <0.9.8

### ISSUE THREAD

**Issue by meyerjom** [binhex/arch-rtorrentvpn#170]
Due to a [bug in rakshasa's libtorrent](https://github.com/rakshasa/libtorrent/issues/167) (which will probably never be fixed), the announce interval is ignored by various trackers. Currently, this container uses rtorrent 0.9.6.
This leads to a noticeable increase in the load on the clients, but especially on the trackers. 

There is a workaround:
Add to (~/.rtorrent.rc):
`throttle.min_peers.normal.set = 0`
`throttle.min_peers.seed.set = 0`

But it would be perfect if the container could use a new rtorrent version directly, e.g. 0.9.8.

regards
Johannes

Besides that: Thank you for your work!

**Comment by binhex** [comment]
This container does not use rtorrent, it uses rtorrent-ps (thus the version is 0.9.6), are you sure this issue is not fixed in rtorrent-ps?, if not then i would encourage you to post an 'issue' on the rtorrent-ps repo.

**Comment by binhex** [comment]
looking further into this rtorrent-ps uses libtorrent-ps, and that looks to be fairly up to date and thus i would expect would include any fixes, are you sure this issue exists in this image?

link to upstream AUR package consumed by this image:- https://aur.archlinux.org/packages/libtorrent-ps/

**Comment by meyerjom** [comment]
Thank you for the quick research and the additional information. The error still occurs at my setup. It looks like it is not even possible that the error is fixed in rtorrent-ps, cause they use the old rtorrent version.

I will open a bugreport at  rtorrent-ps.

**Comment by meyerjom** [comment]
https://github.com/pyroscope/rtorrent-ps/issues/132

**Comment by meyerjom** [comment]
Seems like the rtorrent-ps development is dead. Is there a chance that it will be replaced?

**Comment by binhex** [comment]
there was a commit to master branch 6 days ago, it doesnt look like development is dead to me.

**Comment by triqster1** [comment]
To be fair this was just one commit to change a download URL. The commits throughout 2020 are all just some changes to the dockerfile or build script. Hardly qualifies as new development. And rtorrent has seen updates since 0.9.6 with several merges from rtorrent-ps and issues fixed that are still most likely still valid in rtorrent-ps like this particular issue.

**Comment by meyerjom** [comment]
I see it similarly. The use of this old version of RTorrent puts an extraordinary strain on trackers, which is not good for the tracker ecosystem.

**Comment by binhex** [comment]
ok guys, i wll take a look at this, i may have a test tagged image for you to play with and give me some feedback sometime in the near future.

**Comment by binhex** [comment]
'test' tagged image is now available, please pull down and let me know how you get on with it.

**Comment by meyerjom** [comment]
First impression after 20 minutes of testing: Looks good! I'll get back to you tomorrow with an updated feedback. Thanks for your work!

**Comment by meyerjom** [comment]
The new version is much more resource-efficient and very stable at my machine. I would bring this into the master, with the note that manual rtorrent config changes could lead to problems.

**Comment by binhex** [comment]
new image including rtorrent v0.9.8 is now tagged as 'latest', please pull down and test all ok.

**Comment by meyerjom** [comment]
Works smooth, thanks!

**Comment by binhex** [comment]
sorry guys, i hate to be the bearer of bad news, but i have had to revert back to rtorrent-ps, two reasons, firstly there is a rather nasty bug in 0.9.8 which causes issues when trackers go offline, most often seen with public torrents (https://github.com/rakshasa/rtorrent/issues/999) and secondly i have reliance on pyrocore right now to improve security, which tbh i had completely forgotten about.

so we are back to as it was, if you want to carry on using ver 0.9.8 then you will need to use the tag 'v0.9.8-01' going forward for now at least, it will be 0.9.6 rtorrent-ps fork.

**Comment by adamwinn** [comment]
So what's the plan going forward since rtorrent-ps isn't active anymore?

**Comment by newadventure079** [comment]
@binhex any updates since rtorrent-ps is dead?
