### ISSUE TITLE
Unable to access webui

### ISSUE THREAD

**Issue by mouzzampk2014** [binhex/arch-rtorrentvpn#173]
Hi, apologise if someone already raised this or its just config issue on my side but since last update I am unable to access the webui via 192.168.1.24:9080 but I can access it https://mydomain.com/rutorrent

I am not sure what changed, but was working perfectly fine. Nothing in the logs too.

Thank you

**Comment by ajhorvath20** [comment]
I am having exactly same issue. I posted on different channel too just to check if anything I messed it up with reverse proxy.

**Comment by gabbyendo** [comment]
I'm having the same issue after an update. Can you elaborate on how you got https://mydomain.com/rutorrent to work? That doesn't work for me.

**Comment by gabbyendo** [comment]
> Hi, apologise if someone already raised this or its just config issue on my side but since last update I am unable to access the webui via 192.168.1.24:9080 but I can access it https://mydomain.com/rutorrent
> 
> I am not sure what changed, but was working perfectly fine. Nothing in the logs too.
> 
> Thank you

how did you get the mydomain.com to work? Is that a config you have to enable somewhere?

**Comment by binhex** [comment]
This has been resolved, please pull down tag 'latest'
