### ISSUE TITLE
Fails to start on Synology Devices "FATAL: kernel too old"

### ISSUE THREAD

**Issue by ColoradoPoster303** [binhex/arch-rtorrentvpn#175]
The latest version (rtorrent-ps-1.1.r54.ga787dd9-1-30) fails to start on Synology devices, returning an error code:
```
FATAL: kernel too old
```

Specifics:
1. I am using a DS916+
2. This is with docker-compose + ovpn configuration
3. I have a script that restarts my containers daily, so I am confident this change happened on the latest version
4. I run other binhex containers on the same Synology device, specifically TransmissionVPN and its also on the latest version and NOT affected - starts fine.
5. I've seen reports of this elsewhere, for example [here](https://forums.unraid.net/topic/46127-support-binhex-rtorrentvpn/?do=findComment&comment=952875)

Synology runs an ancient kernel (3.10.105) that hopefully can still be supported

**Comment by binhex** [comment]
duplicate:- https://github.com/binhex/arch-delugevpn/issues/256#issuecomment-787224078
