### ISSUE TITLE
Can not connect to webui

### ISSUE THREAD

**Issue by genebeck** [binhex/arch-rtorrentvpn#177]
Both rtorrent and qbittorrent suddenly stopped working this morning.  This is docker install on a newer Synology box.  From what I can digest from the log file, the docker container is running and vpn is connecting.  It is impossible to connect to the webui or do anything with the install.  I created and new install in a new location and double checked all the settings has the very same results. 

 I had a similar issue in the past when there was an issue with PIA, so I started thinking this was just another VPN issue.  Now I think this is something else.  From what I can see in the logs, PIA is granting an IP.

My PIA subscription was soon to expire and I signed up to PrivateVPN and downloaded their OpenVPN config files and replaced the old PIA files.  Once again, it appears to pull a remote ip but the webui is still down.

I have included a zip of the supervisor log.  The local network is 192.168.0.0 and the docker is static on 192.168.0.225.  At this point I am clueless on what is wrong and what else you will need to troubleshoot this.

[supervisord.zip](https://github.com/binhex/arch-rtorrentvpn/files/6132026/supervisord.zip)

**Comment by theotherp** [comment]
I need to wait at least a minute, often longer for the UI to load.

**Comment by genebeck** [comment]
Interesting enough, both the rtorrent and the qbittorrent started working today.  I am thinking that the issue is PIA was not working and the kill switch was shutting down everything.  While my PIA windows app was working, I suspect the opvn config was not connecting.

Something else I discovered, if the host will not ping, the container will not start.  I was trying to get the package to work with PrivateVPN without out much success.  What appeared to be happening is not all of their hosts will ping and those that will not ping will not work.  Ones that will ping, I can use and the container runs.
