### ISSUE TITLE
[AirVPN] [Synology] VPN configuration file does not contain 'remote' line

### ISSUE THREAD

**Issue by Aerya** [binhex/arch-rtorrentvpn#184]
Hi,

I try to use your binhex/arch-rtorrentvpn:latest with AirVPN on a Synology NAS (latest DSM7).
Container in bootloop: 
```
2021-07-24 08:43:10.179942 [info] VPN_PROV defined as 'airvpn'
2021-07-24 08:43:10.222376 [info] OpenVPN config file (ovpn extension) is located at /config/openvpn/AirVPN_Netherlands_TCP-443.ovpn
2021-07-24 08:43:10.301127 [crit] VPN configuration file /config/openvpn/AirVPN_Netherlands_TCP-443.ovpn does not contain 'remote' line, showing contents of file before exit...
```

I followed reqs as provided for AirVPN provider.

```
docker run -d \
    --cap-add=NET_ADMIN \
    --restart always \
    -p 9080:9080 \
    -p 9443:9443 \
    -p 8118:8118 \
    --name=rtorrentvpn \
    -v /volume1/mnt/torrents:/data \
    -v /volume1/docker/rtorrentvpn:/config \
    -v /etc/localtime:/etc/localtime:ro \
    -e VPN_ENABLED=yes \
    -e VPN_PROV=airvpn \
    -e VPN_CLIENT=openvpn \
    -e ENABLE_PRIVOXY=yes \
    -e ENABLE_AUTODL_IRSSI=no \
    -e ENABLE_RPC2=yes \
    -e ENABLE_RPC2_AUTH=yes \
    -e ENABLE_WEBUI_AUTH=yes \
    -e RPC2_USER=xx\
    -e RPC2_PASS=xx\
    -e WEBUI_USER=xx\
    -e WEBUI_PASS=xx\
    -e LAN_NETWORK=0.0.0.0/0 \
    -e NAME_SERVERS=10.0.4.98 \
    -e DEBUG=true \
    -e PHP_TZ=Europe/Paris \
    -e UMASK=000 \
    -e PUID=0 \
    -e PGID=0 \
    --label=com.centurylinklabs.watchtower.enable=true \
    binhex/arch-rtorrentvpn:latest
```

Here's my AirVPN_Netherlands_TCP-443.ovpn
```
[...]
client
dev tun
remote nl.vpn.airdns.org 443
resolv-retry infinite
nobind
persist-key
persist-tun
auth-nocache
route-delay 5
verb 3
push-peer-info
setenv UV_IPV6 yes
remote-cert-tls server
cipher AES-256-CBC
comp-lzo no
proto tcp
key-direction 1
[...]
```

**Comment by binhex** [comment]
I need a full log to diagnose the issue further, please do the following:- https://github.com/binhex/documentation/blob/master/docker/faq/help.md

**Comment by Aerya** [comment]
Already had it. Here is a sample: https://pastebin.com/mJ4r6ua7
It's the same schema every seconds as the container is in bootloop due to the error.

**Comment by binhex** [comment]
ok please check the ovpn file you think its using is the actual file its using, i have seen this numerous times with users, the path according to your run is:-
```/volume1/docker/rtorrentvpn/AirVPN_Netherlands_TCP-443.ovpn```

the other thing to check is line endings, it should be set to LF not CRLF.

**Comment by Aerya** [comment]
Well it works out of the box on any Linux system. Synology is like UNRAID, modded Linux, sh*t OSes to try to use them as real Linuxes.
Thanks anyway, I just wanted to try Torrenting & VPN at home. I'll use my servers as usually ;)
