### ISSUE TITLE
Constant crashes related to autodl-irssi

### ISSUE THREAD

**Issue by a3m5** [binhex/arch-rtorrentvpn#189]
I've been getting constant crashes with the same (or at least very similar) error as [Issue 137](https://github.com/binhex/arch-rtorrentvpn/issues/137), limiting my uptime to only seconds to minutes before it crashes again, after using arch-rtorrentvpn for 18+ months with no issues. Is autodl-irssi still just not supporting PHP 7?

If there's still no resolution in that regard, is there a way to uninstall or disable autodl-irssi? I couldn't find documentation on Google that worked for this.

Error message for reference:

2021-11-20 08:30:12,413 DEBG 'rutorrent-script' stderr output:

2021/11/20 08:30:12 [error] 1715#1715: *800 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to access array offset on value of type bool in /usr/share/webapps/rutorrent/plugins/autodl-irssi/getConf.php on line 54PHP message: PHP Notice:  Trying to access array offset on value of type bool in /usr/share/webapps/rutorrent/plugins/autodl-irssi/getConf.php on line 61" while reading response header from upstream, client: 172.20.0.1, server: localhost, request: "GET /plugins/autodl-irssi/getlines.php?cid=1227979929&_=1637414988534 HTTP/1.1", upstream: "fastcgi://127.0.0.1:7777", host: "x.x.x.x:9080", referrer: "http://x.x.x.x:9080/"

**Comment by spencerhughes** [comment]
I'm getting this exact same error

**Comment by a3m5** [comment]
I'll note I've changed the flag for ENABLE_AUTODL_IRSSI to **no**

**Comment by binhex** [comment]
last commit to autodl_irssi was over a year ago, i think its dead Jim, do as @a3m5 suggests and disable it.

**Comment by spencerhughes** [comment]
So in my usage the error still happens even when you change that ENV var.

**Comment by a3m5** [comment]
I didn't communicate my thought clearly - I am having the same issue as @spencerhughes.

I changed the flag for ENABLE_AUTODL_IRSSI to **no** and I'm still have crashes.

**Comment by binhex** [comment]
@a3m5 what is the crash? Logs please

**Comment by a3m5** [comment]
Hi binhex, the error I'm getting now actually does seem unrelated, but is still happening fairly frequently:

2021/12/16 07:46:03 [error] 2781#2781: *2077 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "POST /RPC2 HTTP/1.1", upstream: "scgi://127.0.0.1:5000", host: "192.X.X.X:9080"

**Comment by binhex** [comment]
yah thats rtorrent crapping out, it does that sadly, generally when under load,  i've spent a LOT of hours trying to improve stability but its still a bit crud im afraid, that is just part and parcel of using rtorrent.

**Comment by a3m5** [comment]
Ah damn, ok. Would throwing some more resources at it possibly help? And if so, do you know if this is more memory or CPU oriented?

**Comment by binhex** [comment]
> Ah damn, ok. Would throwing some more resources at it possibly help? And if so, do you know if this is more memory or CPU oriented?

it doesnt seem to help, nope, i dont think its a resource issue.

**Comment by a3m5** [comment]
Understood. I'm closing this out, thanks for the replies.
