### ISSUE TITLE
Running this container on remote server (not on same LAN network)

### ISSUE THREAD

**Issue by natoriousbigg** [binhex/arch-rtorrentvpn#21]
This container seems to be more designed to be use at home on the same local LAN (in Unraid) where your server (running UNRAID) resides. However, I'm using it on remote server running Ubuntu. It works great but the issues I'm running into is remote access to the rutorrent webui. In order to access the webui I have to add my IP address that's assigned by my ISP to the LAN_NETWORK environmental variable. But when my IP address changes or if I'm at a different location, I need to update this variable. I believe your IPTABLES rules works well to prevent leakage and to prevent access to port 5000 (rtorrent scgi_port) except by the local network. But I need access to the webui from outside the LAN network as well. Is there a way to separate the LAN_NETWORK variable for port 5000 and web port 9080/9443/3000 which are already password protected by nginx?

**Comment by MartinAyla** [comment]
I would like to know this as well, please.

I am trying to access the rtorrent web ui from outside my LAN and it doesn't work, even though I have forwarded the port in my router.

Any ideas?

**Comment by Fma965** [comment]
+1 to that :)

**Comment by FWoelffel** [comment]
+1

**Comment by Xyaren** [comment]
Same here.
I am not able to access any webui from outside my local network. Portforwarding  is set up and working. (Tested with a ngix container)

**Comment by quoije** [comment]
https://forums.lime-technology.com/topic/44108-support-binhex-general/?tab=comments#comment-433613

**Comment by quoije** [comment]
Same, I thought it was firewalld that was given me trouble at first but it worked well with other containers. I tried this: https://forums.lime-technology.com/topic/44108-support-binhex-general/?tab=comments#comment-433613
 and it didn't work on my server. (Centos 7)

**Comment by binhex** [comment]
Please don't confused the OP with issues related to firewalling and/or iptable mangle module missing. 

Unless you are using a virtual private server and your host is directly connected to the internet (as in you do NOT have a internal private network) then your issue is not the same and will be able to connect to the webui, if you can't then you have issues related to firewall on the host, no port forwarding setup or no iptable mangle module support on your host.

**Comment by quoije** [comment]
Yeah, I didn`t read he was using Unraid, my bad.

**Comment by binhex** [comment]
He isn't running it on unraid, he is running it on a VPS (ubuntu), unless you host is directly connected to the internet and you have no LAN then your issue is different to the OP and should be posted as a separate issue.

**Comment by binhex** [comment]
im afraid i wont be fixing this any time soon, i dont have a VPS and i dont have the time to investigate, sorry guys, closing for now.
