### ISSUE TITLE
Bad response from server: (0[error,tasklist])

### ISSUE THREAD

**Issue by akizzle** [binhex/arch-rtorrentvpn#22]
Been getting this error. After reloading my webpage a bunch of times "sometimes" it goes away. I've read online that we might have to increase the memory in Apache? Anyone else have this issue?

This is in the rutorrent webui.

**Comment by binhex** [comment]
ive not seen that particular error, and btw we arent using apache, its nginx, i will keep an eye out for it

**Comment by akizzle** [comment]
Thank you. do we know how much ram is being allocated? Maybe done through NGINX or PHP?

**Comment by binhex** [comment]
its set to 512 MB for php.ini, how many torrents have you got running?, also this issue looks interesting, again pointing at possible resource issues with ram:-

https://github.com/SynoCommunity/spksrc/issues/2422

**Comment by akizzle** [comment]
I have about 90 torrents running. Not nearly as 5000 like that other user.  I can try making those edits as well.

**Comment by akizzle** [comment]
Do not see an option to edit memory in the rtorrent.rc file.
Already set to 512M here - /etc/php/php.ini 
Location does not exist - /usr/local/etc/php56/php.ini

**Comment by akizzle** [comment]
**Get this from Accessing rtorrent through a VPN**
rtorrent WebUI:
[05.04.2017 14:02:34] WebUI started.
[05.04.2017 14:02:35] Bad response from server: (0 [error,getplugins])

Terminal Debug:
2017-04-05 18:02:35,793 DEBG 'rutorrent-script' stderr output:                                          
2017/04/05 18:02:35 [crit] 943#943: *2 open() "/var/lib/nginx/fastcgi/2/00/0000000002" failed (13: Permi
ssion denied) while reading upstream, client: 172.17.0.1, server: localhost, request: "GET /php/getplugi
ns.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:7777", host: "10.25.10.10:9080", referrer: "http://10.2
5.10.10:9080/"    

**And this is when I access it from home**
rtorrent WebUI:
[05.04.2017 14:05:01] WebUI started.
[05.04.2017 14:05:04] Bad response from server: (0 [error,tasklist])

Terminal Debug:
2017-04-05 18:05:02,006 DEBG 'rutorrent-script' stderr output:                                          
2017/04/05 18:05:02 [error] 943#943: *31 FastCGI sent in stderr: "PHP message: PHP Warning:  rename(/usr
/share/webapps/rutorrent/share/users/admin/settings/uisettings.json.tmp,/usr/share/webapps/rutorrent/sha
re/users/admin/settings/uisettings.json): No such file or directory in /usr/share/webapps/rutorrent/php/
setsettings.php on line 20" while reading response header from upstream, client: 172.17.0.1, server: loc
alhost, request: "POST /php/setsettings.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:7777", host: "10.2
5.10.10:9080", referrer: "http://10.25.10.10:9080/"                                                     
                                                                                                        
2017-04-05 18:05:02,423 DEBG 'rutorrent-script' stderr output:                                          
2017/04/05 18:05:02 [error] 943#943: *69 FastCGI sent in stderr: "PHP message: PHP Warning:  rename(/usr
/share/webapps/rutorrent/share/users/admin/settings/uisettings.json.tmp,/usr/share/webapps/rutorrent/sha
re/users/admin/settings/uisettings.json): No such file or directory in /usr/share/webapps/rutorrent/php/
setsettings.php on line 20" while reading response header from upstream, client: 172.17.0.1, server: loc
alhost, request: "POST /php/setsettings.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:7777", host: "10.2
5.10.10:9080", referrer: "http://10.25.10.10:9080/"                                                     
                                                                                                        
2017-04-05 18:05:03,671 DEBG 'rutorrent-script' stderr output:                                          
2017/04/05 18:05:03 [crit] 943#943: *113 mkdir() "/var/lib/nginx/fastcgi/6/00" failed (13: Permission de
nied) while reading upstream, client: 172.17.0.1, server: localhost, request: "POST /plugins/_task/actio
n.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:7777", host: "10.25.10.10:9080", referrer: "http://10.25
.10.10:9080/"

**Comment by binhex** [comment]
can you please post your docker run command your using

**Comment by akizzle** [comment]
Running it in a Synology. 

![capture](https://cloud.githubusercontent.com/assets/26396617/24726616/0e1c9bd4-1a21-11e7-8fd1-fe0928fa3b4b.PNG)
![capture1](https://cloud.githubusercontent.com/assets/26396617/24726621/114bf00c-1a21-11e7-8e5f-2340a22c5ee7.PNG)

**Comment by binhex** [comment]
> Running it in a Synology.

that explains it, Synology devices have issues with nginx, currently the only way around it is to turn off apparmor, you will also most likely need to load all the required kernel modules too, try stopping the container and then execute the following and then start it again:-

`insmod /lib64/modules/tun.ko
insmod /lib64/modules/iptable_mangle.ko
insmod /lib64/modules/xt_mark.ko
##Disabling apparmor
/usr/syno/etc.defaults/rc.sysv/apparmor.sh stop`

**Comment by akizzle** [comment]
Doesn't look like that did the trick :( 

Weird that over VPN I get a different error. 

![capture](https://cloud.githubusercontent.com/assets/26396617/24753420/04f90c48-1aa0-11e7-9419-5a0b1d0801fb.PNG)
![capture1](https://cloud.githubusercontent.com/assets/26396617/24753423/06b19b54-1aa0-11e7-9cbf-84e075e1562d.PNG)

**Comment by akizzle** [comment]
Error when accessing it through a VPN.

![capture2](https://cloud.githubusercontent.com/assets/26396617/24753556/9e7dae82-1aa0-11e7-9857-3fe0712d4fbb.PNG)

**Comment by akizzle** [comment]
I mean it does look like a permissioning issue. Is there anything else I can try?

2017-04-06 12:16:59,152 DEBG 'rutorrent-script' stderr output:                                          
2017/04/06 12:16:59 [crit] 2282#2282: *849 mkdir() "/var/lib/nginx/fastcgi/1/01" failed (13: **Permission 
denied**) while reading upstream, client: 172.17.0.1, server: localhost, request: "POST /plugins/_task/act
ion.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:7777", host: "10.25.10.10:9080", referrer: "http://10.
25.10.10:9080/"

**Comment by binhex** [comment]
ok so the below is a bug in rutorrent, i dont think it causes any issues from what i can see:-

```
DEBG 'rutorrent-script' stderr output:
2017/04/05 18:05:02 [error] 943#943: *31 FastCGI sent in stderr: "PHP message: PHP Warning: rename(/usr
/share/webapps/rutorrent/share/users/admin/settings/uisettings.json.tmp,/usr/share/webapps/rutorrent/sha
re/users/admin/settings/uisettings.json): No such file or directory in /usr/share/webapps/rutorrent/php/
setsettings.php on line 20"
```

so looks like it got fixed, but its possible its not included in the latest release yet:-
https://github.com/Novik/ruTorrent/pull/1243

**Comment by fryfrog** [comment]
Can you add `--security-opt apparmor:unconfined` to your run options?

**Comment by akizzle** [comment]
Not sure how to do that within the synology interface.

**Comment by akizzle** [comment]
Based on this forum post. I've already done this. https://forum.synology.com/enu/viewtopic.php?t=118103
