### ISSUE TITLE
rTorrent becomes defunct

### ISSUE THREAD

**Issue by theimmortal68** [binhex/arch-rtorrentvpn#23]
I am running this container on an Arch Linux system.  After about 24 hours, rtorrent stops working inside the container.  When I perform a `ps aux | grep torrent` it shows: `[rtorrent main] <defunct>`.  I am unable to stop or restart the docker container and unable to kill the process.  My only solution so far is to completely delete the docker container (which doesn't remove the defunct process) and recreate it.  Please advise how I can resolve this issue, or if there is a better way to recover from it.  Thank you!

**Comment by binhex** [comment]
OK so all my images include a init manager to reap zombie processes, it looks like for some reason this isnt working for you (defunct is a zombie process), my suspicion is that you are overriding the init manager via the docker run command, are you issuing either of the following?:-

```
--init                           Run an init inside the container that forwards signals
                                 and reaps processes
--init-path string               Path to the docker-init binary
```

if this is the case then remove any override and the init manager included (Tini) will take care of any reaping required.

**Comment by theimmortal68** [comment]
I am using this as my docker run command:

**Comment by theimmortal68** [comment]
sudo docker run -d \
    --cap-add=NET_ADMIN \
    -p 9080:9080 \
    -p 9443:9443 \
    -p 8118:8118 \
    -p 3000:3000 \
    -p 5000:5000 \
    --name=rtorrentvpn \
    -v /mnt/Media/Docker/rtorrentpvn/data:/data \
    -v /mnt/Media/Docker/rtorrentpvn/config:/config \
    -v /mnt/Media/Downloads:/mnt/Media/Downloads \
    -v /etc/localtime:/etc/localtime:ro \
    -e VPN_ENABLED=yes \
    -e VPN_REMOTE=europe.vpn.airdns.org \
    -e VPN_PORT=443 \
    -e VPN_PROTOCOL=udp \
    -e VPN_DEVICE_TYPE=tun \
    -e VPN_PROV=airvpn \
    -e ENABLE_PRIVOXY=no \
    -e ENABLE_FLOOD=both \
    -e LAN_NETWORK=192.168.1.0/24 \
    -e NAME_SERVERS=8.8.8.8,8.8.4.4 \
    -e DEBUG=false \
    -e PHP_TZ=America/Los_Angeles \
    -e UMASK=000 \
    -e PUID=1000 \
    -e PGID=100 \
    --restart=always \
    binhex/arch-rtorrentvpn

**Comment by binhex** [comment]
hmm ok that run command looks fine, no ref to init so it shouldnt be overriding it, what version of docker are you using? output of `docker info` please

**Comment by theimmortal68** [comment]
docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad9
8ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4
f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.10.16-1-ck-haswell
Operating System: Antergos Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.3GiB
Name: MediaServer
ID: WWM4:EW5E:JOQN:HDGH:TDLX:OX4L:HNWH:EOZI:JLKY:
6GGG:U5MZ:QYHW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpu shares support

**Comment by binhex** [comment]
Cannot replicate, closing issue
