### ISSUE TITLE
Cannot open tun/tap

### ISSUE THREAD

**Issue by akizzle** [binhex/arch-rtorrentvpn#24]
Setting up Docker on a Cent OS VM and seeing this error in the supervisor.log

2017 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such device (errno=19) Wed May 24 10:10:02 2017 Exiting due to fatal error

Any help would be greatly appreciated. 

Below is the command I ran to get the container started:
docker run -d \
    --cap-add=NET_ADMIN \
    -p 9080:9080 \
    -p 9443:9443 \
    -p 8118:8118 \
    -p 3000:3000 \
    --name=rtorrentvpn \
    -v /opt/rtorrent/data:/data:z \
    -v /opt/rtorrent/config:/config:z \
    -v /etc/localtime:/etc/localtime:ro \
    -e VPN_ENABLED=yes \
    -e VPN_REMOTE=america.vpn.airdns.org \
    -e VPN_PORT=443 \
    -e VPN_PROTOCOL=udp \
    -e VPN_DEVICE_TYPE=tun \
    -e VPN_PROV=airvpn \
    -e ENABLE_PRIVOXY=yes \
    -e ENABLE_FLOOD=both \
    -e LAN_NETWORK=10.25.10.0/24 \
    -e NAME_SERVERS=8.8.8.8,8.8.4.4 \
    -e DEBUG=true \
    -e PHP_TZ=America/New_York \
    -e UMASK=000 \
    -e PUID=1000 \
    -e PGID=1000 \
    binhex/arch-rtorrentvpn

**Comment by akizzle** [comment]
Looks like i resolved it by including the --privileged flag but is there a way to do this without including the flag?

**Comment by binhex** [comment]
You can either set the privileged flag or use cap-add=NET_ADMIN but you have to set one or the other, no way around it
