### ISSUE TITLE
Pausing state. 

### ISSUE THREAD

**Issue by akizzle** [binhex/arch-rtorrentvpn#27]
When Sonarr/Radarr sent a DL request the file sits in the pausing state and doesn't actually download

Running on a freshly imaged CentOS 7 vm.

docker run -d \
    --privileged \
    --cap-add=NET_ADMIN \
    -p 9080:9080 \
    -p 9443:9443 \
    -p 8118:8118 \
    -p 3000:3000 \
    --name=rtorrentvpn \
    -v /home/rtorrent/data:/data:z \
    -v /home/rtorrent/config:/config:z \
    -v /etc/localtime:/etc/localtime:ro \
    -e VPN_ENABLED=yes \
    -e VPN_REMOTE=america.vpn.airdns.org \
    -e VPN_PORT=443 \
    -e VPN_PROTOCOL=udp \
    -e VPN_DEVICE_TYPE=tun \
    -e VPN_PROV=airvpn \
    -e ENABLE_PRIVOXY=yes \
    -e ENABLE_FLOOD=both \
    -e LAN_NETWORK=10.25.10.0/24 \
    -e NAME_SERVERS=8.8.8.8,8.8.4.4 \
    -e DEBUG=true \
    -e PHP_TZ=America/New_York \
    -e UMASK=000 \
    -e PUID=0 \
    -e PGID=0 \
    binhex/arch-rtorrentvpn.

**Comment by akizzle** [comment]
Quick update. This only happens when files are sent through radarr/sonarr. If I manually add the .torrent file in rtorrent it works.

**Comment by akizzle** [comment]
Figured out what the issue but still don't understand why.

In sonarr/radarr i had rtorrent configured as a localhost. When I configured it via IP no issues.

**Comment by 0mni** [comment]
Hate to bring up an old issue, but I am currently experienceing the same issue, I did have Sonarr configured to use rtorrent as localhost, and I did change it to an ip of 127.0.0.1 but still getting this error.  Anyone have any suggestions?

**Comment by akizzle** [comment]
Hey 0mni,

Change the IP to the actually IP address of the host not the localhost IP. 

That's what did it for me.

**Comment by 0mni** [comment]
I was able to fix it, it was my own fault.  In Sonarr, I still had the location of my previous rtorrent download directory:
/mnt/disk1/torrent/download/tv

But in the docker, its actually:
/data/torrent/download/tv

Turned out it had nothing to do with the localhost/127.0.0.1 or the actual IP of the docker.

Completely missed that, thanks for the reply, hopefully this will help someone else who has this issue, could be either or :)

**Comment by binhex** [comment]
Glad its fixed :-) just to confirm the reason why localhost/127.0.0.1 won't work, you have to keep in mind although the container is running on localhost its running in bridge mode not actually directly on the host, so thus you always need to connect other applications by using the ip address of the host and the port mapping.

oh and btw dont try and switch the network mode from 'bridge' to 'host', this would cause the iptable rules i have defined to be run on the host and could then cause you to be locked out of remote access to the host.
