### ISSUE TITLE
webui error.

### ISSUE THREAD

**Issue by akizzle** [binhex/arch-rtorrentvpn#29]
Seeing this in the log when I access rtorrent through the webui. I just pulled a new image and built a new container.  I don't see any errors in the supervisor.log Not showing the values of my downloads/seeds/uploads. Running docker on CentOS7 which is fully up to date.

[08.07.2017 10:49:17] WebUI started.
[08.07.2017 10:49:18] JS error: [http://10.25.10.7:9080/js/webui.js : 1923] Uncaught TypeError: Cannot read property 'radarr' of undefined

![image](https://user-images.githubusercontent.com/26396617/27986333-f3dc2326-63cb-11e7-9fea-095d305b0462.png)

**Comment by akizzle** [comment]
Error went away when I disabled the httprpc plug-in.

**Comment by fryfrog** [comment]
Dumb question, but how do you disable the httprpc plugin?

**Comment by inkubux** [comment]
Thanks it worked.
