### ISSUE TITLE
Downloads completion directory won't change

### ISSUE THREAD

**Issue by FedoraTipper** [binhex/arch-rtorrentvpn#3]
Hey,

Is there a way to change the default directory for when downloads finish? Currently once a download is finished it gets moved to /data/completed instead of the custom directory that I have set. I do have Autotools enabled, but has not made any difference. So I'm guessing that there is a hidden config setting for this that I have yet to find. I took away the comment mark of system.method.set_key and changed the directory, yet the downloads still stick to the default /data/completed. ruTorrent also states 
Save As:	/data/Completed/XXX in the general tab.

**Comment by binhex** [comment]
So rutorrent is purely a web frontend to rtorrent, and as such does NOT modify any settings, the only settings you can save using rutorrent are settings for rutorrent itself, i.e. things like enabling/disabling plugins, settings for plugins etc.

If you want to modify things like incoming port, enabling/disabling dht, and folders for incomplete/complete downloads then you will have to modify the rtorrent config file, this is located in /config/rtorrent/config/rtorrent.rc please make sure you use something like notepad++ (not notepad) to prevent windows line endings getting added.

**Comment by FedoraTipper** [comment]
That's not the issue. The issue is that no matter what change I make to completed downloads line. It doesn't change at all, something is causing it to move to /Completed regardless of what I put there.

**Comment by FedoraTipper** [comment]
I found the "bug", rutorrent doesn't report that there is already and instance of autotools working. This instance looks like it gets started on the startup script, or at the bottom of the rc file. The automove feature is unchecked, even though it still running the background. 

When you have the instance in the background as well as rutorrent's feature being checked again (basically creating another autotools instance), it actually breaks all completed downloads and deletes it or copies itself in a subfolder again.

I like the vpn idea, but the major problem with this docker is that settings are confusing and annoying. Knowing that rutorrent is just a frontend, it should at least report the correct settings instead of creating it's own. A normal rtorrent+rutorrent, allows you to edit from rtorrent's side perfectly fine. When the docker is reset, all current settings become rewritten from /config/r(u)torrent/config..., and this is what I think is causing the above problem.

I know complaining isn't helping, but I've sat countless hours trying to figure this out.

**Comment by binhex** [comment]
i hear what your saying, the issue i was attempting to fix by the reload of initplugins.php (which then loads other rutorrent plugins) is the problem where there is a race condition, such that the initplugins.php scvript can run before rtorrent is correctly up and running and thus it doesnt initialise any of the background plugins, this is a major pain as it then doesnt run the scheduler or rss feed plugins.

i haven't seen your particular issue i have to say but im wiling to accept it could occur, thus i have come up with a neater solution to this by breaking this out into a separate script which then monitors for nginx, once up the script will run once and hopefully this should result in consistent initialisation of the plugins.

**Comment by binhex** [comment]
OK new docker image built, please give it a whirl if you get the time.

**Comment by FedoraTipper** [comment]
Sorry about the previous rage.

Digging deeper, it looks like users that were deleted still have plugin control. To fix this, I had to recreate the deleted user and uncheck all options in rutorrent's plugin menu. Once that's done, I deleted the user and everything looks sorted.

**Comment by binhex** [comment]
ahh right ok thanks for posting back. Well i think my latest tweak is still valid as it reduces the need to reinitialise the plugins so im happy to keep that in place. I will close this issue for now, if you think there is anything else to add to this particular issue then please post back.
