### ISSUE TITLE
autodl-irssi addition

### ISSUE THREAD

**Issue by bamtan** [binhex/arch-rtorrentvpn#30]
Thank you so much for this Docker binhex!

Is there any chance you could add the auto-dl plugin to this? I'm just reopening this issue since the other one is closed for no obvious reason. 
https://github.com/autodl-community/autodl-irssi
+ the rutorrent plugin which goes with it
https://github.com/autodl-community/autodl-rutorrent

This Docker might be of assistance, too
https://hub.docker.com/r/xeroxmalf/rutorrent-autodl-irssi/~/dockerfile/

Kind regards

**Comment by binhex** [comment]
Ok I will take a look and see how hard it is to implement

**Comment by binhex** [comment]
well it took a bit longer than expected, but i got there in the end, got diverted onto other stuff. 

so download the latest image and add in environment variable key named "ENABLE_AUTODL_IRSSI" and set the value to "yes" to enable, example command updated in readme.md

**Comment by bamtan** [comment]
Fantastic work binhex, thank you very much!

Though, this update seems to have removed the plugins folder -- anyway I can access the folder to modify+add plugins?

**Comment by binhex** [comment]
im working on a better mechanism for plugins, in short i was seeing corruption and plugins mismatch, and working out how to copy in the autodl-irssi plugin was the last straw, so decided to for a cleaner approach of keeping the standard plugins in the container and work out a method of allowing users to copy across just the additional ones they need (currently working on it).

**Comment by bamtan** [comment]
ah great, thanks for your work again binhex !
