### ISSUE TITLE
Error: No OpenVPN config file located in /config/openvpn/

### ISSUE THREAD

**Issue by alias1** [binhex/arch-rtorrentvpn#31]
Fresh download/install of this, running on unraid with PIA as the provider.

```
2017-09-17 11:42:51.236088 [crit] No OpenVPN config file located in /config/openvpn/ (ovpn extension), please download from your VPN provider and then restart this container, exiting...
```

Setup instructions seem to imply there shouldn't be anything that needs doing aside from configuring PIA user/pass?

**Comment by binhex** [comment]
yes you now need to download the ovpn file, see here:- https://github.com/binhex/arch-delugevpn/issues/33

**Comment by alias1** [comment]
That makes sense. In #33 you mention updating the documentation around this, if they haven't landed already, would be good for future.

Since the PIA openvpn download link hasn't changed (in as long as i've used it), I wonder if it'd be possible to add a log line near that error, when PIA is enabled, saying to go download it manually/etc:

* https://www.privateinternetaccess.com/openvpn/openvpn.zip
* https://www.privateinternetaccess.com/openvpn/openvpn-strong.zip

Or at least link to a wiki page/similar on this repo explaining where to get them for PIA?
