### ISSUE TITLE
Port Issues

### ISSUE THREAD

**Issue by RaymondSchnyder** [binhex/arch-rtorrentvpn#33]
Hey,

i tried to run this behind a Firewall, and i allowed the following ports on ALL protocols:
1190 - 1200

But when openvpn starts, it seems not to connect to the PIA Server.

Are there any ports besides the web interface ports (i dont allow the 9*** ports as i have a nginx reverse setup) i need to allow just for the VPN to work? 

Thanks

**Comment by fryfrog** [comment]
Firewalls don't normally bock *outbound* ports, are you sure you're doing that?

**Comment by binhex** [comment]
the only port you need to allow is the port used by the endpoint you are connecting to, and dns in order to resolve the endpoint hostname. you will of course also need to allow the ip address of the endpoint your connecting to which may/will change every time you connect.
