### ISSUE TITLE
Make an arch-qbittorrentvpn?

### ISSUE THREAD

**Issue by fryfrog** [binhex/arch-rtorrentvpn#35]
I hate suggesting this here, but I don't see any other reasonable way of sending a suggestion. I've read that qbittorrent is pretty good, but haven't tried it. Is your framework portable enough that creating a vpn version wouldn't be a big undertaking? Or maybe you've already tried qbittorrent and it isn't great?

I'm still hoping for a torrent daemon as good as nzbget or sabnzbd. :/

**Comment by binhex** [comment]
It isn't trivial unfortunately, and unless there is a good reason to do this over using rtorrent or deluge then i'm afraid it isn't going to happen.

**Comment by fryfrog** [comment]
Fair enough. I'll install it and see if it is 10x better than Deluge / rTorrent (I doubt it).
