### ISSUE TITLE
[Feature Request] Track Labels for ruTorrent

### ISSUE THREAD

**Issue by FedoraTipper** [binhex/arch-rtorrentvpn#4]
Hey,

Do you mind adding track labels to the default plugin install? [TrackLabels](https://github.com/Novik/ruTorrent/tree/master/plugins/tracklabels)

**Comment by binhex** [comment]
ok i will take a look when i get a bit of time.

**Comment by binhex** [comment]
ok so after having a look through my code it looks like i have had historic issues with the track labels plugin causing instability with rutorrent/rtorrent and thus i remove it at install time. im a little bit loathed to have this re-enabled for all users, esp if it does cause instability, so for now im going to recommend you download and install it yourself.

if you want to try this plugin out then you can grab it from here https://github.com/Novik/ruTorrent/archive/master.zip and unzip it and copy the tracklabels plugin folder to /config/rutorrent/plugins/ then restart rutorrent and make sure its enabled and you should be be good, just watch out for crashes!.
