### ISSUE TITLE
Flood wont reverse proxy.

### ISSUE THREAD

**Issue by si0972** [binhex/arch-rtorrentvpn#44]
The changes for baseuri in config.js doesnt catch propperly. Adding `/flood` just gets me the loading screen. 
![image](https://user-images.githubusercontent.com/7110194/36304645-ad114fee-1310-11e8-8581-624981429c2a.png)
Using a simple config like
```nginx
    location /flood {
		add_header X-Frame-Options SAMEORIGIN;
        proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://10.0.0.11:3002;
        }
```
yields the same as on LAN.

**Comment by joshuajbrunner** [comment]
change baseURI to 

`baseURI: '/flood/',`

change your location block to this

```
port_in_redirect off;

location /flood/ {
  rewrite ^/flood/(.*) /$1 break;
  proxy_pass http://10.0.0.11:3002;
}
```

Let me know if that works for you
