### ISSUE TITLE
chown and chmod are kind of overkill on launch

### ISSUE THREAD

**Issue by GottZ** [binhex/arch-rtorrentvpn#51]
#chown -R "${PUID}":"${PGID}" /etc/webapps /usr/share/webapps /usr/share/nginx/html /etc/nginx /etc/php /run/php-fpm /var/lib/nginx /var/log/nginx /etc/privoxy /home/nobody /etc/webapps/flood /usr/share/autodl-irssi
    #chmod -R 775 /etc/webapps /usr/share/webapps /usr/share/nginx/html /etc/nginx /etc/php /run/php-fpm /var/lib/nginx /var/log/nginx /etc/privoxy /home/nobody /etc/webapps/flood /usr/share/autodl-irssi

[go here](https://github.com/binhex/arch-rtorrentvpn/blob/0.9.6-3-177/build/root/install.sh#L190-L191) to see what i mean.

most of these directories only need read only access anyways. it delays startup quite some minutes and creates unnecessary overlay attributes in docker for the running container.

anyways.. i love this image. thanks for creating this.

**Comment by binhex** [comment]
>  it delays startup quite some minutes 

you must have an insanely slow host then, the delay is near instantaneous for me, taking i would guess around 1-2 second to process both commands, i can go from startup to running within 20 seconds or less on a very modest host.

> creates unnecessary overlay attributes in docker

not exactly sure what you mean by this?, if you are referring to increasing the size of the container then i don't think this is true, i have seen no evidence of container growth over time.

**Comment by GottZ** [comment]
i'm seeding terrabytes of torrents successfully with this. while it also does dozen other tasks. i'd not say the host is slow.

this:  
```
echo running chown
date
chown -R "${PUID}":"${PGID}" /etc/webapps /usr/share/webapps /usr/share/nginx/html /etc/nginx /etc/php /run/php-fpm /var/lib/nginx /var/log/nginx /etc/privoxy /home/nobody /etc/webapps/flood /usr/share/autodl-irssi
echo running chmod
date
chmod -R 775 /etc/webapps /usr/share/webapps /usr/share/nginx/html /etc/nginx /etc/php /run/php-fpm /var/lib/nginx /var/log/nginx /etc/privoxy /home/nobody /etc/webapps/flood /usr/share/autodl-irssi
echo done
date
```
results in this:

    running chown
    Wed 25 Apr 14:12:00 CEST 2018
    running chmod
    Wed 25 Apr 14:44:15 CEST 2018
    done
    Wed 25 Apr 14:44:15 CEST 2018

docker info:

```
root@tesla /compose/rtorrent # docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 18.04.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.35-1-lts
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 1.457GiB
Name: tesla
ID: 4VUV:EAQC:P2YF:IRZT:CURF:BJBK:O4LY:WM7L:HCKM:D6YY:LKVE:OE47
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

docker compose config:
```
root@tesla /compose/rtorrent # cat docker-compose.yml
version: '3.4'

services:
  rtorrent:
    image: binhex/arch-rtorrentvpn
    # cap_add, security_opt, and volume required for the image to function
    container_name: rtorrent
    cap_add:
      - net_admin
    ports:
      - 9080:9080
      - 9443:9443
      - 8118:8118
      - 3000:3000
    environment:
      VPN_ENABLED: 'yes'
      VPN_PROV: 'custom'
      VPN_USER: 'xxxxxxxxxx'
      VPN_PASS: 'xxxxxxxxxx'
      ENABLE_PRIVOXY: 'yes'
      ENABLE_FLOOD: 'yes'
      ENABLE_AUTODL_IRSSI: 'yes'
      LAN_NETWORK: '10.13.37.0/24'
      NAME_SERVERS: '1.1.1.1,1.0.0.1,8.8.8.8,8.8.0.0,9.9.9.9'
      DEBUG: 'false'
      PHP_TZ: 'UTC'
      UMASK: '000' # i'm seeding / leeching from a cifs share
      PUID: '0' # required if you skip chmod / chown
      PGID: '0' # required if you skip chmod / chown
    restart: unless-stopped
    volumes:
      - ./data:/data:rw
      - ./config:/config:rw
      - /etc/localtime:/etc/localtime:ro
      - ./init.sh:/root/init.sh:ro # needed to skip chmod / chown upon container boot
      - ./iptable.sh:/root/iptable.sh:ro # needed for incomming connections to rtorrent through vpn for better seeding
```

how it looks after it finished:

![htop](https://user-images.githubusercontent.com/559564/39247882-e56f46ce-489a-11e8-9f7e-8d168eba304c.png)

when the chown is running it barely touches any resources.

this is running as a vm inside bhyve inside freebsd.
the host runs a zfs pool on 4x 4tb hdd's with a raidz configuration.
the vm hdd is attached through iscsi into the zfs pool
the rtorrent data is linked to some directories within my zfs pool through cifs 1
the host itself does nothing except running this vm and providing smb and some other protocols.

it's running on a HP Proliant Microserver Gen 8 containing a Intel(R) Xeon(R) CPU E31260L @ 2.40GHz and 16 GB ECC ram.

what filesystem are you using in your docker configuration?

as you can see i'm using overlay2. i know in fact that this can make a difference.

**Comment by binhex** [comment]
> why so salty?

Sorry i didn't mean to come across rude, i was just very surprised it takes that long on your host, here is the same commands as you executed running on my host (specs of host later on):-

```
running chown
Wed 25 Apr 16:39:14 BST 2018
running chmod
Wed 25 Apr 16:39:14 BST 2018
done
Wed 25 Apr 16:39:14 BST 2018
```

As you can see its so fast that you can't see a difference when using command date, so using 'time':-

```
[root@b4e8a68d90c0 tmp]# ./test.sh 
running chown
Wed 25 Apr 16:41:45 BST 2018

real    0m0.216s
user    0m0.013s
sys     0m0.191s
running chmod
Wed 25 Apr 16:41:45 BST 2018

real    0m0.157s
user    0m0.020s
sys     0m0.136s
done
```
so it took less than half a second to complete both commands.

docker info:-

```
Containers: 11
 Running: 9
 Paused: 0
 Stopped: 2
Images: 11
Server Version: 17.09.1-ce
Storage Driver: btrfs
 Build Version: Btrfs v3.17
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.35-unRAID
Operating System: Slackware 14.2
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 15.41GiB
Name: Tower
ID: 27K5:Y4QH:C7Q6:QVLJ:Y7FB:LJAI:N6BD:CNHI:PHEB:56J3:A3UA:M7NV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

cat /proc/cpuinfo:-

```
model name      : AMD FX(tm)-6300 Six-Core Processor
```

Memory is a very measly 16GB.

I have multiple containers running plus a busy Windows 10 VM on this host.

I can only assume your issues are down to layered virtualization causing overheads (VM running Docker) whereas i am running Docker on bare metal and/or as you mentioned, storage driver btrfs on my host vs overlay2 on yours.

**Comment by GottZ** [comment]
> ive got a proposal for you, how about i only perform chmod during image build, then put checks in place to only run chown if the puid/pgid changes (or on first run of container), that way you would only get hit by the overhead once.

had that in mind too. actually a good idea in general.

i suppose most of these folders would work perfectly fine with read and exec access anyways. so in theory even 555 would be sufficient in most cases.
i guess we would not need that many chown's at all then.
most likely only for logging directories.
i suspect flood slows it down quite a lot since it has quite a lot of files thanks to node_modules. that's just a guess though.

about the btrfs / overlay2 difference, i suspect the fact that overlay2 runs on top of extfs running on top of a virtual block storage device on zfs might slow it down a little.

**Comment by binhex** [comment]
> i suspect the fact that overlay2 runs on top of extfs running on top of a virtual block storage device on top of zfs might slow it down a little.

yeah i reckon!, its not going to help having that many layers for sure, just fyi im running this using unRAID, so its bare metal running slackware os with XFS formatted drives, docker images and containers are then stored in a loopback mounted BTRFS formatted image, which gives surprisingly good performance and means you can locate the image on any underlying filesystem you want.

ok i will implement that proposal then, it should speed things up for you, but maybe you want to think about an alternative method for running docker containers in the future, as im sure it will become a problem down the line at some point.

**Comment by GottZ** [comment]
> as im sure it will become a problem down the line at some point.

i suspect it only really effects access to the vhdd. luckily i map persisted paths in docker containers into cifs mounts.

i truly agree that xfs on the host would speed up any access alot but since i have experienced data fault in the past through aging harddrives i kinda choose zfs to ensure data integrity.
i'm serious. this is especially visible with video files and jpeg pictures. [look here for a wiki entry about it](https://en.wikipedia.org/wiki/Data_degradation)
i highly value the insane iop overhead if data stays intact. maybe i should just change a few zfs parameters and see if i can squeeze a bit more performance out of it. probably requires me to install a small ssd for read / write caching.

zfs is expensive. both in hardware and iops but just as i said, the benefits make it worth it for me as a nas and homeserver solution.

ps: unraid is awesome.

**Comment by binhex** [comment]
ok new image is built, please pull it down and give it a whirl.

what it should now do is it will still run chown on first run, but on subsequent runs it will not run chown unless the value is changed or the container is deleted and re-created. chmod has been moved into the build scripts, so it wont now run chmod on startup.

p.s. i have seen other people bitching on github about performance of overlay2 and aufs when running chown, so it looks like a known bug/limitation for those particular storage drivers, maybe try btrfs?.

**Comment by GottZ** [comment]
> maybe try btrfs?
due to the fact btrfs was essentially born out of the fact that oracle bought sun and zfs pretty much turned proprietary in the process.. you could see btrfs as a alternative to zfs.
essentially btrfs on top of zfs would be insanely high IO overhead.

docker has a zfs storage driver but sadly i'm not running docker on freebsd but a arch linux bhyve vm.

this essentially leaves me with overlay 2 (the defacto default setting in all new docker installations)

i'll push the new image as soon as i find the time. thanks for the efforts so far.

**Comment by binhex** [comment]
I think for now this is as far as i can go with this issue, so im closing it off.
