### ISSUE TITLE
Consider rtorrent-ps?

### ISSUE THREAD

**Issue by fryfrog** [binhex/arch-rtorrentvpn#54]
If we were on IRC or Discord, I'd link to it and ask if you'd considered basing this on it. But instead, I'm just creating an issue. Might be worth looking at? Might not?

¯\\\_(ツ)_/¯

https://github.com/pyroscope/rtorrent-ps

**Comment by binhex** [comment]
Do your have experience of using this over tTorrent? And if so would you say it is more stable? Any other reasons to switch? I'm assuming full computability with rutorrent right?

**Comment by fryfrog** [comment]
I'm not sure yet, since I use your Docker image I'll be sticking with what ever you go with. If you don't have a strong objection to this "improved" version of rTorrent and would be open to including it, I'll be happy to get it setup and see if it might be worth exploring. I was mainly hoping you'd heard of it already and discounted its usage.

Also, you say tTorrent... but you mean rTorrent right? Gotta be a typo! :)

**Comment by binhex** [comment]
i will have a look at this in the future, for now its getting closed.
