### ISSUE TITLE
Commit Issues

### ISSUE THREAD

**Issue by josjaf** [binhex/arch-rtorrentvpn#55]
Hi Binhex. First of all, this container is absolutely fantastic. I've been using it flawlessly for months 👍 

For some reason, ```0f7e25a``` broke my running instance of the container. I pulled the latest and ran docker-compose up -d, but I still don't see the container. When I browse to the container on 9080, I saw Privoxy or it wouldn't respond at all. What logs can I share to help you troubleshoot? 

Thanks!

**Comment by josjaf** [comment]
Changing my image to binhex/arch-rtorrentvpn:0.9.6-5-01 fixed it for me.

**Comment by binhex** [comment]
There have been two subsequent commits since then that should fix the issue (rtorrent 0.9.7 invalidated older style 0.9.6 options in rtorrent.rc).

**Comment by josjaf** [comment]
I pulled 502032c031d597c46ea12fea53c990e756f962d7 and I still had the same problem.

**Comment by binhex** [comment]
Ok can you post the contents of file /config/rtorrent/config/rtorrent.rc
