### ISSUE TITLE
Using arch-rtorrentvpn behind nginx reverse proxy

### ISSUE THREAD

**Issue by fryfrog** [binhex/arch-rtorrentvpn#56]
Could you enable the wiki? Or where would be a smart place to document this? I just spent a couple days trying to get this to work and it turned out to be entirely because nginx was some how trying to process the `.php` files served by nginx embedded in the Docker container. I *fixed* it by only processing `.php` files in `/`.

```
location / {
    include conf.d/php.conf;
}
```

And the reverse proxy settings are crazy simple
```
location /rutorrent/ {
    proxy_pass http://10.0.1.2:9080/;
}
```

I think it might be smarter to *disable* php inside the `/rutorrent/` location, but I'm still figuring out how to do that.

**Comment by binhex** [comment]
Hi fryfrog, i have enabled the wiki and created a new page for this, not sure if you can edit the page or not or how this works for you (first time using wiki on github), so let me know if you need me to copy/paste the contents.

https://github.com/binhex/arch-rtorrentvpn/wiki/Using-arch-rtorrentvpn-behind-nginx-reverse-proxy

**Comment by drkdragonarcher** [comment]
@fryfrog Try using this:
`location ^~ /rutorrent/ {
    proxy_pass http://10.0.1.2:9080/;
}`

**Comment by fryfrog** [comment]
@binhex: I can't edit it :(

@glover279: The important bits are in the opening comment, nothing else I could show would help.

**Comment by binhex** [comment]
@fryfrog re-opened for ya, hopefully that means you can now edit OP

**Comment by fryfrog** [comment]
@drkdragonarcher: Your suggestion totally works too, I finally just tested it. Now to understand why! :)

@binhex: I can wiki now, thanks!

**Comment by drkdragonarcher** [comment]
@fryfrog I believe it's because it makes it ignore other regular expression if it's a better match so if you're running `location ~ \.php$` for FastCGI, the php files for ruTorrent will match it and run through it like you were experiencing and the `^~` basically tells it not to run through the FastCGI block.
