### ISSUE TITLE
Request: Flexget support?

### ISSUE THREAD

**Issue by NoLooseEnds** [binhex/arch-rtorrentvpn#58]
Hi, 

I'm currently migrating away from a dedicated VM to a docker solution, and this docker image is perfect for me (as soon as I get this working). 

The only thing missing for my use case is [Flexget](https://github.com/Flexget/Flexget). Any chance you would like to incorporate Flexget into this?

(I guess I could try to fork it and incorporate it my self, but that would take a while to get up to speed on how to create docker images)

**Comment by binhex** [comment]
Im afraid this wont happen, the docker philosophy is to run a single app in a single container, im already pushing that philosophy and dont want to overload this image with any additional applications.
