### ISSUE TITLE
Sleep causing rtorrent to crash

### ISSUE THREAD

**Issue by FedoraTipper** [binhex/arch-rtorrentvpn#6]
Hey,

Not sure how this is happening all of a sudden for me. It seems that sleep at the end of rtorrent.sh is causing rtorrent to crash. This issue started today. 

Monitored with htop. When 10min sleep is issued as a process, rtorrent will crash 3 seconds after. Standard debug output is returned, no output of a crash happening.

Removed sleep command and rtorrent started to work normally again. Do you perhaps have the same issue?

**Comment by binhex** [comment]
Hi have no idea why removing sleep fixes your issue but im pretty confident that the sleep command is not your issue.

btw removing the sleep will cause a VERY tight while loop which can lead to high cpu usage and possibly other side effects.

**Comment by binhex** [comment]
So what i think is happening is rtorrent is crashing for whatever reason, you then hit the sleep command at the end of the while loop, which then waits up to 10 mins before rechecking rtorrent is running, thus your assuming that the sleep command is killing things, by removing the sleep command you are just rechecking faster that rtorrent process is running.

So what ive done to fix this up is put in some additional code to make the checking and restarting of rtorrent much faster (30 secs), so now even if rtorrent crashes (which it does often) then things will get restarted and you will be off again.

To see the change please pull down the latest image, if you could give me some feedback on the fix that would be great.
