### ISSUE TITLE
Password escaping 

### ISSUE THREAD

**Issue by StevenMatchett** [binhex/arch-rtorrentvpn#60]
While setting up it was unable to authenticate my account because my password contained "!" and a "%" symbol

**Comment by binhex** [comment]
Indeed, this is a known issue and can be seen in the /config/supervisord.log file, unfortunately escaping is not supported in the credentials file for openvpn, so there is currently no way around it other than t ensure the password and username doesnt container any characters that aren't in the rang 0-9 a-z A-Z
