### ISSUE TITLE
Support for ARM architectures

### ISSUE THREAD

**Issue by cilki** [binhex/arch-rtorrentvpn#63]
How difficult would it be to support ARM for this image? It's really convenient to run rtorrent on a Raspberry Pi or NAS (QNAP supports Docker containers).

Looks like [this](https://github.com/linuxserver/docker-rutorrent-armhf) repository managed to do it, but it doesn't have vpn support.

**Comment by binhex** [comment]
you can already run this on QNAP, support for arm though is non trivial, so im afraid it wont get done any time soon.
