### ISSUE TITLE
If /usr/bin/rtorrent crashes the process/container isn't restarted

### ISSUE THREAD

**Issue by gangefors** [binhex/arch-rtorrentvpn#65]
I'm running this on a Synology DS1515+ with 16GB RAM, having some 5000+ torrents in the client at any time. At some point it might happen that the rtorrent process crashes and isn't restarted.

I'd like to propose that the process should be restarted, alternatively it should shut down PID1 and let the container exit then based on the restart setting of the docker parameter the container can be automatically restarted.

Any of these options would solve the issue for me.

**Comment by binhex** [comment]
there is code already in to do this, if the process ends for whatever reason then it will be restarted, there is a delay for this happens, of 30 seconds. i use this container myself and have had it running for months at a time without the need to restart the container, even with power cuts and dropped sessions from my isp it keeps going (including the occasional crash of rtorrent). 

next time it crashes can you firstly wait to see if it comes back, if it doesnt then docker exec into the running container and see if rtorrent process is running or not.

**Comment by gangefors** [comment]
The reason I opened this issue was just because I've logged into the web
ui, got the message that rtorrent isn't running and then checking the
container and there is no rtorrent process to be found. I have to restart
the container to get it running again.

I'll see if I can find some more into. I guess that I can dig into the
rtorrent logs and see what I find there.

This usually happens after 6+ weeks of uptime so it will take some time
before I can fill in some more info.

**Comment by gangefors** [comment]
Shouldn't this read true instead of false? Or do you have some other code that makes rtorrent restart in case of an unexpected exit?

```
...
[program:rtorrent-script]
autorestart = false
...
```

**Comment by binhex** [comment]
no that should be false, supervisord is referencing the rtorrent.sh script not the executable, and we don't want the script being restarted (and in any case it will never fail, unless bash bombs out - unlikely). 

if you want to see the lines of code to monitor and restart take a look here:-

https://github.com/binhex/arch-rtorrentvpn/blob/master/run/nobody/rtorrent.sh

line 75 checks to see if the process is running.

if its not running then line 145 matches and executes, firstly terminating the process on line 154 (this is used in the case of port/ip change) deleting the lock file incase it exists (line 167) and then finally starting the process again (line 174 or 179 depending if user is using pia).

its pretty robust and i cannot currently get into a situation where rtorrent process is down and doesnt get re-created (30 second wait).

**Comment by binhex** [comment]
Alright that makes sense then as to why it's not restarting the process. I will need to rework the spreads in order to incorporate the additional checks that I put in place for the VPN section so leave it with me and I will take a look

**Comment by binhex** [comment]
alright, this was a bigger bit of work than i first thought but its now done, ive tested this and it does now restart rtorrent process if killed, whether the vpn is enabled or not. please pull down the latest image and give it a whirl.
