### ISSUE TITLE
nginx access.log is not rotated

### ISSUE THREAD

**Issue by ssixty** [binhex/arch-rtorrentvpn#67]
Just noticed my access.log was taking up over 700mb.

Not running the absolute latest version but have updated within the past couple months and can't see a previous issue opened for this. Is it a known or resolved issue?

Running on Unraid 6.5.2.

**Comment by khiles** [comment]
definitely an issue i checked mine and was 243mb in size

**Comment by binhex** [comment]
ok i have written a script which will auto rotate the nginx log, so it will result in a maximum of 5 log files, each of which can be a maximum of 10MB, i am just making some further unrelated changes before i create the image.

**Comment by binhex** [comment]
image pushed, looks like it works for me :-)

**Comment by ssixty** [comment]
Thanks, binhex. I'll give it a go when I get chance
