### ISSUE TITLE
Startup permission denied

### ISSUE THREAD

**Issue by ZataH** [binhex/arch-rtorrentvpn#7]
Trying to start this on clean docker host.
My /data is mounted through smb.
I am getting this in supervisor when starting:
chown: changing ownership of '/data/Incomplete': Permission denied

It cant obviously not change permission on a share. But it has the right permissions to overwrite/delete data. 

What can I do?

**Comment by FedoraTipper** [comment]
Your problem might be that smb is running on another user than what docker is running on. Best is to either shift smb to docker's user or shift docker's user to smb. If you use systemd, you can change the user in the .service files.

**Comment by ZataH** [comment]
The smb owner is the same as the one i have stated in puid variable.
The smb mount it mounted to the same user. 

should that not work?

**Comment by FedoraTipper** [comment]
Not sure if setting PUID and GUID will fix this. This seems to be more of a issue with the docker itself and smb ownership. I haven't really used smb with rtorrent before, so I'm even more in the dark then you :sweat_smile:

**Comment by ZataH** [comment]
Well the problem seems to be, that the rtorrent script want to chown, which is cant, since i am running smb. 
The funny thing though, if I run the container in a unraid vm, with remote share to my nas, it is working

**Comment by binhex** [comment]
im looking into this guys

**Comment by binhex** [comment]
this issue is now resolved, i have now put in some additional code to allow this to carry on even if chown/chmod fails for /config, if any issues still then please let me know.
