### ISSUE TITLE
Chown volume

### ISSUE THREAD

**Issue by qtv** [binhex/arch-rtorrentvpn#74]
More of a feature request.

Right now, in the README example there's 
```
 -v /root/docker/data:/data \
 -v /root/docker/config:/config \
```
which creates a /config and /data owned by the PUID/PGID specified. That works.

However, additional volumes I bind are not owned by PUID/PGID and are owned by root:root no matter where I bind them to, which I believe is basic Docker behavior. I would love the specified PUID/PGID to also own additional mounts.

**Comment by GottZ** [comment]
just chown the new mounts manually once and it will work just fine.
the install script does not care about the mounts at all. not even the provided ones.

**Comment by qtv** [comment]
That seems fine.
chown was not working with a virtualbox user system mount; it just did nothing. Messing with a permissions and creating a soft link in /data/ worked fine finally. Although this is still a decent feature, it is not hard to do manually, so likely unnecessary.
