### ISSUE TITLE
Torrents Randomly disappearing after Finished? AutoTools or Rtorrent.rc conflict? 

### ISSUE THREAD

**Issue by restalfep** [binhex/arch-rtorrentvpn#79]
Randomly losing downloads sometimes. On rare occasions a download will finish, get to 100% then just go back to 0% when it is moved to /data/completed/ and then disappear from my file system so it has to redownload. This seems to happen more when the torrent has no label on it. 

I'm not sure if there is some conflict between AutoTools and the default rtorrent.rc or something else. I haven't modified the default rtorrent.rc. 

For AutoTools, I have Path to Finished Downloads: "/data/completed" and AutoWatch feature to "/data/watched"

For Downloads setting in RuTorrent i have the default "/data/incomplete"

**Comment by apetresc** [comment]
I seem to be having this problem too - does the fact that you closed this issue yourself mean you solved it? If so, mind sharing your findings?
