### ISSUE TITLE
adding support for mullvad vpn

### ISSUE THREAD

**Issue by Nanodragon999** [binhex/arch-rtorrentvpn#80]
I Would like to use my mullvad account with this.

**Comment by binhex** [comment]
they're already people using this with that VPN provider all you need to do is download the ovpn file from the provider and put it in the correct place see the readme for details.

**Comment by Nanodragon999** [comment]
i did that, though there isn't a .ovpn file provided by mullvad, so i just renamed the config file to that extension.
Seemed to work, detected the IP of the vpn and everything.
There wasn't any errors in logs, but download didn't seem to work on anything.
Tried using a ubuntu iso to test it, doesn't work.

**Comment by Nanodragon999** [comment]
I recall the port opened on my mullvald account was 24120.
here the command i used:
`	docker run -d \
    --cap-add=NET_ADMIN \
    -p 9080:9080 \
    -p 9443:9443 \
    -p 8118:8118 \
    -p 3000:3000 \
    --name=rtorrentvpn \
    -v /root/docker/data:/data \
    -v /root/docker/config:/config \
    -v /etc/localtime:/etc/localtime:ro \
    -e VPN_ENABLED=yes \
    -e VPN_PROV=custom \
    -e STRICT_PORT_FORWARD=yes \
    -e ENABLE_PRIVOXY=yes \
    -e ENABLE_FLOOD=yes \
    -e ENABLE_AUTODL_IRSSI=yes \
    -e LAN_NETWORK=192.168.1.0/24 \
    -e NAME_SERVERS=209.222.18.222,37.235.1.174,1.1.1.1,8.8.8.8,209.222.18.218,37.235.1.177,1.0.0.1,8.8.4.4 \
    -e DEBUG=false \
    -e PHP_TZ=UTC \
    -e UMASK=000 \
    -e PUID=0 \
    -e PGID=0 \
    binhex/arch-rtorrentvpn`

**Comment by fxjkhr** [comment]
Visit the site <https://mullvad.net/en/download/config/> and make sure Platform = Windows.  This provides you an .ovpn file.  Copy extracted files (mullvad_be.ovpn      mullvad_ca.crt       mullvad_userpass.txt) into /config/openvpn folder.  

Restart the container 👍
