### ISSUE TITLE
Terminal to access irssi occasionally?

### ISSUE THREAD

**Issue by restalfep** [binhex/arch-rtorrentvpn#81]
Is there a way to use the terminal within the docker to access the currently active irssi that is running from autodl-irssi? For example, if I wanted to access it so I can chat temporarily in one of the channels from within the docker? Is irssi running via screen or some other method?

**Comment by GottZ** [comment]
there are several ways to get a shell into the running container.
in my case i can use either of these:

    docker exec -it rtorrent sh
    docker-compose exec rtorrent sh

to list all sessions just do this:

    docker-compose exec rtorrent tmux list-sessions

then to attach to the irssi session just do this:

    docker-compose exec rtorrent tmux attach-session -t irssi_session

to exit the tmux session without killing it:

    ctrl + b
    d

**Comment by restalfep** [comment]
When I try "docker exec -it binhex-arch-rtorrentvpn tmux list-sessions" I get "error connecting to /tmp/tmux-0/default (no such file or directory)". Any idea?
