### ISSUE TITLE
allow removing rutorrent authentication

### ISSUE THREAD

**Issue by guillaumedsde** [binhex/arch-rtorrentvpn#82]
Hi, in my deployment scenario, I'm using an nginx reverse proxy, and handle authentication there, would it be possible to add an option to remove the authentication dialog for rutorrent?

**Comment by khiles** [comment]
If  you go to /appdata/binhex-rtorrentvpn/nginx/security and remove auth file or you could copy your over but just removing that will remove the requirement to login
