### ISSUE TITLE
Flood won't start 

### ISSUE THREAD

**Issue by enoch85** [binhex/arch-rtorrentvpn#87]
As Flood is in development (still missing some features), would it be possible to delete the docker image with `docker rmi rtorrentvpn` and at the same time keep the volumes (containing data, db and stuff), then run the `docker run` command again to fetch the latest Flood changes since it's built on master? Or is that done every time the docker is restarted?

Also, if I want to run the Flood on a different branch than master, where do I change that in the docker build files?

Thanks!

cc @binhex

**Comment by enoch85** [comment]
Hmm, question one should be docker pull. 

And looking at your latest commit I can see that I can change that in the install script now.

**Comment by enoch85** [comment]
OK, so docker pull didn't replace the image. Please help @binhex

**Comment by binhex** [comment]
the procedure for updating a docker container should go like this:-

docker rm -f <container name> # this deletes the container
docker rmi -f <image name> # this deletes the image
docker pull <image name> # this pulls the new image
docker run ... # this creates the container

if you want to automate this then take a look at watchtower:- https://github.com/v2tec/watchtower

btw i wouldnt advise switching branch for flood, its a bit of a car crash at the mo, the only active branch is 'master'.

**Comment by enoch85** [comment]
OK, so something is wrong as I installed watchtower and now when the docker is restarted (since there was a new build available) I can't reach flood anymore. I saw that you made some changes, can you please have a look?

Thanks!

**Comment by binhex** [comment]
hmm looks like things have changed, so its not possible to perform a npm run build during docker build, probably as docker build runs not privileged, so that means i will have to put in some additional code to do a one off post build before flood can start, its going to take a little while to get this sorted, for now you can roll back to the previously tagged image if you like, you can do this by specifying <name of image>:<tagged version you want to run> when you issue the docker run command, so for instance:-

docker run ......binhex/arch-rtorrentvpn:0.9.7-2-05

**Comment by enoch85** [comment]
OK, thanks for confirming @binhex! I'll simply revert my snapshot.

Please let me know when it's done.

**Comment by enoch85** [comment]
It would also be nice if we actually used the Nginx log. It seems like it's not created.

```
2019-01-04 18:16:11,959 DEBG 'watchdog-script' stdout output:
[info] Nginx log file does not exist, skipping log rotation
```

**Comment by binhex** [comment]
> It would also be nice if we actually used the Nginx log. It seems like it's not created.

it is used, its just skipping rotation cos, well you cant rotate a log that doesnt exist :-), once its been created then it will be analysed and if its too large then it will be rotated.

**Comment by enoch85** [comment]
Well, of course. My bad. :)

**Comment by enoch85** [comment]
@binhex Hey, I saw that you made a new commit. Is the issue resolved now?

**Comment by enoch85** [comment]
Just tested and it still doens't work.

**Comment by binhex** [comment]
yep, i might get some time tonight to take a look, but no promises, next commit though will be to address this issue, the previous commit snuck in as a higher priority issue.

**Comment by binhex** [comment]
new image has just been built, please pull it down and give flood a whirl.

**Comment by enoch85** [comment]
Thanks! It works, but I'm "greeted" with this: 
![screenshot from 2019-01-10 21 29 15](https://user-images.githubusercontent.com/4511254/50995335-1c088280-151f-11e9-90a9-b6306fb3e641.png)

I had to manually enter host 0.0.0.0 and port 5000 to connect.

**Comment by enoch85** [comment]
And ALL my RSS is gone! :( I thought they were preserved as the data DIR is persistent?

**Comment by binhex** [comment]
> Thanks! It works, but I'm "greeted" with this:

yeah you will be, thats the initial setup screen in flood, you need to tell it how to connect to rtorrent, keep in mind the previous version of flood is quite old now, so its possible the configuration options have changed and your old config is no longer valid, thus the initial setup screen.

> And ALL my RSS is gone! :( I thought they were preserved as the data DIR is persistent?

how did you setup the rss feeds, using rutorrent perhaps?, make sure its not just a ui issue, switch back to rutorrent, if your rss feeds re-appear then you know thats the issue. To confirm, as long as /config volume mapping is pointing at a persistent location on the host then yes all data is persistent, including rss feeds (confirmed by me).

**Comment by enoch85** [comment]
Thanks!

I added the RSS feeds directly in Flood GUI when I set it up for the first time. I then made a backup of the "feeds.db" which I now tried to copy back to the same file (with correct permissions) in the ../config/flood folder as all settings where gone (including that file) when I updated the image.

I run about 50 RSS feeds, and I'd rather not re-create them upon every time I update the image. Current behavior seems to wipe old settings, which is not an optimal behaviour imho.

Btw, should I use 0.0.0.0 in flood connnection settings (same value as in rtorrent), or would the local server IP be more safe?

**Comment by enoch85** [comment]
Also, even if I add the exact same values back they are not visible in the GUI after a restart of the Docker.

**Comment by enoch85** [comment]
So just to be clear. It seems like it's not oresistent as feeds.db were empty after the update.

Also, I only run Flood on this host.

**Comment by enoch85** [comment]
Hmm, OK. I used watchtower to upgrade with the --cleanup tag.

Maybe some issue in watchtower then. 

Thanks for your help!

**Comment by binhex** [comment]
> Maybe some issue in watchtower then.

no its not a watchtower issue, its the inability of flood to upgrade your rss database from an earlier version (latest github release) to the latest version (github master branch commit).

In theory this COULD happen again but im afraid there is nothing i can do to prevent this, all i do is package up the application, so if the flood developer doesn't bother to migrate existing config to the new version (and this is in heavy dev so they may not) then you will/may loose configuration. 

If this is too much of a risk for you then i encourage you to switch to rutorrent which is a much more stable and mature web ui, the choice is yours.
