### ISSUE TITLE
I'm actually struggling with this exact issue on Ubuntu 16.04.5

### ISSUE THREAD

**Issue by aspeer06** [binhex/arch-rtorrentvpn#88]
I'm actually struggling with this exact issue on Ubuntu 16.04.5
No local firewall and confirmed multiple times on edge firewall that it's configured properly.
Works internally perfect but externally I get nothing.

from supervisord.log
[info] iptable_mangle support detected, adding fwmark for tables

FWIW my network is a 10.0.0.0/8 defined so the VPN tun0 exists within my internal address space.

_Originally posted by @aspeer06 in https://github.com/binhex/arch-rtorrentvpn/issue_comments#issuecomment-451621451_

**Comment by binhex** [comment]
> FWIW my network is a 10.0.0.0/8 defined so the VPN tun0 exists within my internal address space.

that is most probably your issue.

**Comment by aspeer06** [comment]
Any hints as to an easy fixe besides moving my network/modifying the vpn instance and iptable mangles?

**Comment by fryfrog** [comment]
Why in the *world* are you running a `/8` internally? That is * 16,777,214* IPs. Try switching to something more sane? Using a `/16` is still a crazy number of IPs, but it might get you out of the tun0 range.

**Comment by aspeer06** [comment]
I'm not sure why using a 10.0.0.0/8 network is being questioned. It's quite a common configuration and ton's of universities where this is extremely applicable are configured this way. It allows for ample address space growth for the multitude of personal devices that end up registering with our network as well as roaming from AP to AP. I can switch it I just was wanting to bring it to the attention that an option for a different internal net range might be useful in such a scenario and wasn't sure if any of the functionality was in the image or even feasible. 

That said I have fixed it by reducing the available to address space to exclude the tun0 address subnet which seems to have solved the immediate issue.

**Comment by fryfrog** [comment]
Ah, I just assumed home network use. It does seem reasonable to allow selection of tunnel network/mask. I believe the "vpn" portion is another project, I've submitted a few patches to @binhex and had them accepted/merged. I bet if you made it work, he'd accept.

**Comment by aspeer06** [comment]
I need to take the time to learn more about the docker networking stack and I may do just that as a learning exercise. I assume the biggest issue would be a misconfiguration of it would completely hose the stack...
