### ISSUE TITLE
How to enable rpc?

### ISSUE THREAD

**Issue by gotjoshua** [binhex/arch-rtorrentvpn#9]
What would be needed to enable xmlrpc? (for example, to access via couchpotato)

thanks for the great docker image - i got it running via docker-compose real easily!

**Comment by gotjoshua** [comment]
Ok, so after digging around in the config files a bit i discovered this:
When flood is enabled, xmlrpc will succeed the test but fail in real communication (via couchpotato rtorrent downloader using my.ip.add.res:5000)
When flood is off, xmlrpc will pass the test and function properly to send torrents to rtorrent (using my.ip.add.res:9080/RPC2) (evident [here](https://github.com/binhex/arch-rtorrentvpn/blob/master/config/nobody/nginx/config/nginx.conf#L73))

It seems that the RPC2 routing has not been added to the flood nginx config - is that true?

**Comment by binhex** [comment]
when flood is enabled it disables rutorrent, which is probably why your seeing the failure when cp tries to communicate, if you need both running then you can set the value for key ENABLE_FLOOD to "both", this allows both rutorrent and flood to run at the same time.

**Comment by binhex** [comment]
assuming issue is fixed, please re-open if this isnt the case.

**Comment by icebal** [comment]
set ENABLE_FLOOD to both, flood is running but rutorrent and RPC2 both are not running. this causes (most importantly for me) transdrone not able connect. turned debug on and not seeing anything rutorrent related in the supervisord.log

**Comment by gotjoshua** [comment]
@icebal, i'm not sure whats going wrong for you. I don't use transdrone, but I have ENABLE_FLOOD set to both and I can:
1) use rutorrent and flood simultaneously ([with some peculiarities](https://github.com/binhex/arch-rtorrentvpn/issues/12))
2) connect to rtorrent RPC from couchpotato via the following url pattern: ```<ru.torr.ent.ip>:port/RPC2```
(in the newer versions of couchpotato they have a separate field for RPC2 path so you leave it off the URL)

so RPC2 is actually accessible 'via' rutorrent, which seems to be accomplished by mapping a path to a specific port in the nginx conf [section now starting at line 73](https://github.com/binhex/arch-rtorrentvpn/blob/master/config/nobody/nginx/config/nginx.conf#L73)

**Comment by icebal** [comment]
rebuilt the container again, it seems rutorrent is running, but complains
about not connecting to rtorrent. This is the same issue that pushed me to
flood, so it seems everything is fine here :)

**Comment by binhex** [comment]
just to add that i have no issues using transdroid (github name of transdrone with optional search feature) with flood and rutorrent enabled or just rutorrent, it just works for me. if you cant get rutorrent to connect to rtorrent on startup then you have a configuration issue, i can assure it does work. post your supervisord.log file (located in /config) and i will take a look, watch out for credentials.

**Comment by icebal** [comment]
Its the timeout for rutorrent that is my issue, reason I went to the flood
UI. Ill get the logs and post them. As far as the configs, they are the
default.

**Comment by binhex** [comment]
ok not sure when your were seeing the timeout issues but i have recently (in the last week or so) put in additional code to speed up the restarting of rtorrent on a crash (which is does do from time to time) so the original issue you were seeing may not now exist, so it might be worth trying to run with rutorrent again and see if things have improved for you.

**Comment by binhex** [comment]
closing issue, no further feedback from user.
