### ISSUE TITLE
Stuck at rutorrent plugins initalized

### ISSUE THREAD

**Issue by qtv** [binhex/arch-rtorrentvpn#90]
https://spit.mixtape.moe/view/bc87c91e

I updated the image, last one was about 3 months ago, and did an overall system upgrade. The new container now does not get past ruTorrent plugins initialised. accessing rutorrent through the web interface works, but all the torrents are stuck at "Queued" and they do not ever actually check, even if you do a force recheck. Any thoughts? Nothing changed except updating...

**Comment by qtv** [comment]
I'm afraid that did not fix anything.

**Comment by binhex** [comment]
@qtv follow the procedure in the link below please and attach log here:-

https://forums.unraid.net/topic/44108-support-binhex-general/?do=findComment&comment=435831

**Comment by qtv** [comment]
[supervisord.log](https://github.com/binhex/arch-rtorrentvpn/files/2785737/supervisord.log)
I did specify the environment variable with `-e DEBUG=true` as well as in my local bash but not noticing a difference in the logs really. Hopefully it's alright.

**Comment by binhex** [comment]
this is wrong:-

`2019-01-22 23:57:43.452598 [info] LAN_NETWORK defined as '10.0.2.15/24'`

see here Q4. for how to configure LAN_NETWORK:- https://forums.unraid.net/topic/44108-support-binhex-general/?tab=comments#comment-433613

**Comment by qtv** [comment]
@binhex Thank you for that, fixed, although networking was not an issue before with that setting. Nothing changes in regards to the problem but attached the new log anyway.
[supervisord.log](https://github.com/binhex/arch-rtorrentvpn/files/2788703/supervisord.log)

**Comment by qtv** [comment]
I can confirm a resolution. Two files did not have the correct permissions, which seemed to hang the entire rtorrent. I changed the directory of the files to the correct permissions and now have a working rtorrent. Not what I expected to happen with a limited permission issue. Thanks for all who helped.
