### ISSUE TITLE
Problem setting baseURI for Flood

### ISSUE THREAD

**Issue by NoLooseEnds** [binhex/arch-rtorrentvpn#92]
Hi, I've set the baseURI for Flood, but it does not get applied. 
When I try to load the https://hostname/flood it loads, but all the assets are located under `/static` instead of `/flood/static` so the page is just blank.

HTML output:
```
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name="theme-color" content="#000000"><link rel="manifest" href="/manifest.json"><link rel="shortcut icon" href="/favicon.ico"><title>Flood</title><link href="/static/css/main.16a9269d.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="app"></div><script type="text/javascript" src="/static/js/main.ef1b8922.js"></script></body></html>
```
config.js
```
// This is the configuration file for Flood, a React-based frontend for the
// rtorrent BitTorrent client.
// Copy this file to ./config.js and make changes below.
// config.js must exist before running `npm run build`.

const CONFIG = {
  // This URI will prefix all of Flood's HTTP requests. You _must_ have a web
  // server, like nginx, configured to forward these requests to the Flood
  // web server.
  // For example, if you intend to serve from http://example.com/flood, set this to
  // '/flood' and configure your web server to pass _all_ requests from `/flood` to
  // the root of Flood's web server.
  // Recompiling assets with `npm run build` is needed after each `baseURI` change.
  // See https://github.com/jfurrow/flood/wiki/Using-Flood-behind-a-reverse-proxy
  baseURI: '/flood/',
  // Flood uses a local nedb database to keep track of users, torrents,
  // and activity. The database is regularly purged to remove outdated data.
  // This value dictates how old data is, in milliseconds, before being purged.
  dbCleanInterval: 1000 * 60 * 60,
  // Where to store the local nedb database.
  dbPath: '/config/flood/db/',
  // The host that Flood should listen for web connections on.
  // If you want to connect to Flood from hosts other that the one it is running
  // on, you should change this value.
  // To listen on all interfaces, change to `floodServerHost: '0.0.0.0',
  floodServerHost: '0.0.0.0',
  // The port that Flood should listen for web connections on.
  floodServerPort: 3000,
  // Used for development. See the "Local Development" section of README.md
  // for detail.
  floodServerProxy: 'http://127.0.0.1:3000',
  // Flood keeps a history of torrent download and upload speeds.
  // This value dictates the number of individual records per period to keep.
  maxHistoryStates: 30,
  // How often (in milliseconds) Flood will request the torrent list from.
  torrentClientPollInterval: 1000 * 2,
  // A unique secret for signing messages with JWT (see https://jwt.io). Change
  // this to something unique and hard to guess.
  secret: 'flood',
  // Configuration for SSL, if using SSL with the Flood service directly.
  ssl: false,
  sslKey: '/config/nginx/certs/host.key',
  sslCert: '/config/nginx/certs/host.cert',
};
// Do not remove the below line.
module.exports = CONFIG;
```

log output:
```
[info] Copying Flood config file /config/flood/config/config.js back to container...
2019-02-04 20:46:38,582 DEBG 'flood-script' stdout output:
2019-02-04 20:46:39,519 DEBG fd 17 closed, stopped monitoring <POutputDispatcher at 140379457331784 for <Subprocess at 140379457335024 with name flood-script in state RUNNING> (stdout)>
2019-02-04 20:46:39,520 DEBG fd 21 closed, stopped monitoring <POutputDispatcher at 140379459222920 for <Subprocess at 140379457335024 with name flood-script in state RUNNING> (stderr)>
2019-02-04 20:46:39,520 INFO exited: flood-script (exit status 0; expected)
```
Any advice on this?

**Comment by GottZ** [comment]
i absolutely recommend using a subdomain.

flood.example.com

**Comment by NoLooseEnds** [comment]
Why do you recommend a subdomain over a hostname? 

Anyhow, that's not the issue.

**Comment by GottZ** [comment]
then try this: https://github.com/jfurrow/flood/issues/284#issuecomment-284266416

why i recommend a subdomain over a hostname? erm.. you are aware a hostname can be a subdomain?

just saying.. https://flood.home.gottz.de/

why add complexity through messing with baseuri if you can just use a sub domain.

**Comment by NoLooseEnds** [comment]
Yes, I am aware, but you probably understood what I meant?

The issue here is not if I would use a subdomain or not, but to be able to modify baseURI in the Flood config and get it to stick).

It's not always the best to take the path with the least resistance – especially not in the long run.

So if anyone has any input on the actual issue, I would be happy.

**Comment by enoch85** [comment]
Abandon Flood, use ruTorrent. :)

**Comment by NoLooseEnds** [comment]
I just like the Flood GUI, but I might have to if I want this docker setup to work.

Anyhow, I got it to build. I edited the flood.sh file to build flood upon start – it adds a bit more time, but it works.

The problem now is that changing the baseURI and combining that with Traefik apparently breaks something. https://github.com/jfurrow/flood/issues/761#issue-405344965

I've tested a lot of docker images, both combined ones (like this with rtorrent and flood in one) and separate with rtorrent in one, flood in another, but it's still the same problem.

**Comment by fryfrog** [comment]
Could you just skip the URL base? You don't *need* it, even though it does make life nicer...

**Comment by GottZ** [comment]
i agree that baseuri should indeed work out of the box since it's not hard to keep it in mind during development.
now due to the fact flood does not seem to like baseuri, i'd advice using a sub domain.
why?
because this is a non issue today.
you even get ssl wildcard domains for free today.
adding a dns record is a non issue too.
additionally you also remove cookie leakage with subdomains.

we are in 2019. stop using baseuri.

**Comment by fryfrog** [comment]
You don't even have to resort to a sub domain, just do your reverse proxy right and you can still use a `/path`. This is what I use in nginx for the handful of daemons that don't support urlbase:

```
location /qbittorrent/ {
    proxy_pass http://10.0.1.2:8060/;
}
```

You usually don't need the trailing `/` in both the location and proxy_pass, but some require it.

**Comment by enoch85** [comment]
Nginx Reverse Proxy + subdomain = best setup IMHO.  You'll get the protection form both the subdomain CNAME and the extra layer that the Nginx Reverse Proxy would bring.

**Comment by GottZ** [comment]
@fryfrog i wonder about that though. this only works if the backend cannot handle baseuri but does not if the frontend is incapable
