### ISSUE TITLE
Hide nginx server version

### ISSUE THREAD

**Issue by enoch85** [binhex/arch-rtorrentvpn#93]
Hi!

Would be nice if you could hide the server version for Nginx (when using ruTorrent) with `server_tokens off;`

Thanks!

**Comment by binhex** [comment]
done, obviously this will only work for new users, for existing users they will need to manually put that setting in their existing nginx config files if they want to hide nginx version.

**Comment by enoch85** [comment]
Thanks!

Quick question, are my RSS feeds preserved when running ruTorrent on an image update?

**Comment by binhex** [comment]
Yes they should be
