### ISSUE TITLE
add File Manager for ruTorrent

### ISSUE THREAD

**Issue by enoch85** [binhex/arch-rtorrentvpn#96]
I successfully added File Manager to ruTorrent in my setup. I think this should be default in this docker.

Basically:
- clone repo from [here](https://github.com/nelu/rutorrent-thirdparty-plugins).
- Replace `/config/rutorrent/user-plugins/filemanager/conf.php` (with cat maybe) with this content:
```
<?php

$fm['tempdir'] = '/tmp';		// path were to store temporary data ; must be writable 
$fm['mkdperm'] = 755; 		// default permission to set to new created directories

// set with fullpath to binary or leave empty
$pathToExternals['rar'] = '/usr/sbin/unrar';
$pathToExternals['tar'] = '/usr/sbin/tar';
$pathToExternals['bzip2'] = '/usr/sbin/bzip2';
$pathToExternals['gzip'] = '/usr/sbin/gzip';
$pathToExternals['zip'] = '/usr/sbin/zip';
$pathToExternals['unzip'] = '/usr/sbin/unzip';

// archive mangling, see archiver man page before editing

$fm['archive']['types'] = array('rar', 'zip', 'tar', 'gzip', 'bzip2');




$fm['archive']['compress'][0] = range(0, 5);
$fm['archive']['compress'][1] = array('-0', '-1', '-9');
$fm['archive']['compress'][2] = $fm['archive']['compress'][3] = $fm['archive']['compress'][4] = array(0);




?>
```
Or just add the full paths to all the `$pathToExternals` variables
- Add the default root path according to [this](https://github.com/nelu/rutorrent-thirdparty-plugins/issues/17)

**Comment by flatmapthatshit** [comment]
It works. 
For zip and rar support we'll need the respective packages to be included in https://github.com/binhex/arch-rtorrentvpn/blob/master/build/root/install.sh

**Comment by flatmapthatshit** [comment]
I've managed to get everything working locally. 

## Filemanager

### Extra packages:

https://www.archlinux.org/packages/extra/x86_64/zip/
https://aur.archlinux.org/packages/rar/

###  /config/rutorrent/user-plugins/filemanager/conf.php
```php
<?php

$fm['tempdir'] = '/tmp';		// path were to store temporary data ; must be writable 
$fm['mkdperm'] = 755; 		// default permission to set to new created directories

// set with fullpath to binary or leave empty
$pathToExternals['rar'] = '/usr/bin/rar';
$pathToExternals['unrar'] = '/usr/bin/unrar';
$pathToExternals['tar'] = '/usr/bin/tar';
$pathToExternals['bzip2'] = '/usr/bin/bzip2';
$pathToExternals['gzip'] = '/usr/bin/gzip';
$pathToExternals['zip'] = '/usr/bin/zip';
$pathToExternals['unzip'] = '/usr/bin/unzip';

// archive mangling, see archiver man page before editing

$fm['archive']['types'] = array('rar', 'zip', 'tar', 'gzip', 'bzip2');




$fm['archive']['compress'][0] = range(0, 5);
$fm['archive']['compress'][1] = array('-0', '-1', '-9');
$fm['archive']['compress'][2] = $fm['archive']['compress'][3] = $fm['archive']['compress'][4] = array(0);




?>
```

## Fileshare

### /config/nginx/config/nginx.conf

Add the following code to both `server` blocks (http and https):

```
        location = /files/share {
            include fastcgi.conf;
            fastcgi_pass          127.0.0.1:7777;
            fastcgi_param SCRIPT_FILENAME /usr/share/webapps/rutorrent/plugins/fileshare/share.php;
        }
````

### /config/rutorrent/user-plugins/fileshare/share.php

Remove or comment the file bellow:

    if(getConfFile('config.php') === FALSE) {die('No such file');}

### /config/rutorrent/user-plugins/fileshare/conf.php

Set the full share URL, including hostname or public IP. Example:

    $downloadpath = 'http://mydomain.com/files/share';

-----

IMO, `fileupload` and `mediastream` are no longer useful. I have deleted both plugins.

**Comment by binhex** [comment]
3rd party plugins can be installed by the user, i wont be including anything additional to the stock plugins at this time.
