### ISSUE TITLE
Waiting for rTorrent to start listening

### ISSUE THREAD

**Issue by silentArtifact** [binhex/arch-rtorrentvpn#97]
I've gotten things more-or-less configured, but when I launch the container, things seem to stall out at `[info] Waiting for rTorrent process to start listening on port 5000`. It never seems to progress beyond that. Any thoughts?

**Comment by OBenned** [comment]
Got the same problem, i tried disabling the VPN and then it worked

**Comment by binhex** [comment]
that is a symptom of rtorrent not starting, which is normally an indication that the vpn tunnel is not established, i am going to need full logs to debug, please follow the procedure in the following link and attach the log here:-

https://forums.unraid.net/topic/44108-support-binhex-general/?do=findComment&comment=435831

**Comment by binhex** [comment]
no response, closing.
